import { Locale, locales } from "./i18n";

export const blogPostIds = ["formats-guide", "safe-download-guide"] as const;
export type BlogPostId = (typeof blogPostIds)[number];

export type BlogSection = {
  id: string;
  title: string;
  paragraphs: string[];
  bullets?: string[];
};

export type BlogPost = {
  id: BlogPostId;
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  readTime: string;
  published: string;
  updated: string;
  keywords: string[];
  intro: string[];
  sections: BlogSection[];
  faqs: { question: string; answer: string }[];
  ctaTitle: string;
  ctaText: string;
  ctaLabel: string;
};

export const blogSeoTitles: Record<Locale, Record<BlogPostId, string>> = {
  fr: { "formats-guide": "MP4 ou MP3 : quel format choisir ?", "safe-download-guide": "Télécharger une vidéo en ligne en sécurité" },
  en: { "formats-guide": "MP4 vs MP3: Which Format Should You Choose?", "safe-download-guide": "Download Video Online Safely: Complete Guide" },
  ar: { "formats-guide": "MP4 أم MP3: دليل اختيار الصيغة", "safe-download-guide": "دليل تنزيل الفيديو عبر الإنترنت بأمان" },
  es: { "formats-guide": "MP4 o MP3: ¿qué formato elegir?", "safe-download-guide": "Cómo descargar vídeo online con seguridad" },
  pt: { "formats-guide": "MP4 ou MP3: qual formato escolher?", "safe-download-guide": "Como baixar vídeo online com segurança" },
  de: { "formats-guide": "MP4 oder MP3: Welches Format wählen?", "safe-download-guide": "Videos online sicher herunterladen" },
};

export const blogUi: Record<Locale, {
  nav: string;
  home: string;
  title: string;
  subtitle: string;
  kicker: string;
  latest: string;
  read: string;
  minRead: string;
  published: string;
  updated: string;
  contents: string;
  questions: string;
  related: string;
  converter: string;
  footer: string;
}> = {
  fr: { nav: "Blog", home: "Accueil", title: "Guides vidéo et audio", subtitle: "Des explications précises pour choisir un format, préserver la qualité et télécharger un contenu public de manière responsable.", kicker: "Centre de ressources", latest: "Guides à la une", read: "Lire le guide", minRead: "min de lecture", published: "Publié le", updated: "Mis à jour le", contents: "Dans ce guide", questions: "Questions fréquentes", related: "À lire ensuite", converter: "Ouvrir le convertisseur", footer: "Guides pratiques sur les formats, la qualité et l’utilisation responsable des médias publics." },
  en: { nav: "Blog", home: "Home", title: "Video and audio guides", subtitle: "Clear, practical explanations for choosing a format, preserving quality and handling public media responsibly.", kicker: "Resource center", latest: "Featured guides", read: "Read the guide", minRead: "min read", published: "Published", updated: "Updated", contents: "In this guide", questions: "Frequently asked questions", related: "Read next", converter: "Open the converter", footer: "Practical guides to media formats, quality and responsible use of public content." },
  ar: { nav: "المدونة", home: "الرئيسية", title: "أدلة الفيديو والصوت", subtitle: "شروحات عملية لاختيار الصيغة والحفاظ على الجودة والتعامل المسؤول مع الوسائط العامة.", kicker: "مركز المعرفة", latest: "أدلة مختارة", read: "اقرأ الدليل", minRead: "دقائق قراءة", published: "نُشر في", updated: "حُدث في", contents: "في هذا الدليل", questions: "الأسئلة الشائعة", related: "اقرأ أيضاً", converter: "افتح المحول", footer: "أدلة عملية حول الصيغ والجودة والاستخدام المسؤول للمحتوى العام." },
  es: { nav: "Blog", home: "Inicio", title: "Guías de vídeo y audio", subtitle: "Explicaciones claras para elegir formato, conservar la calidad y utilizar contenido público de forma responsable.", kicker: "Centro de recursos", latest: "Guías destacadas", read: "Leer la guía", minRead: "min de lectura", published: "Publicado", updated: "Actualizado", contents: "En esta guía", questions: "Preguntas frecuentes", related: "Sigue leyendo", converter: "Abrir el convertidor", footer: "Guías prácticas sobre formatos, calidad y uso responsable de contenido público." },
  pt: { nav: "Blog", home: "Início", title: "Guias de vídeo e áudio", subtitle: "Explicações claras para escolher o formato, preservar a qualidade e usar conteúdo público com responsabilidade.", kicker: "Central de recursos", latest: "Guias em destaque", read: "Ler o guia", minRead: "min de leitura", published: "Publicado em", updated: "Atualizado em", contents: "Neste guia", questions: "Perguntas frequentes", related: "Leia também", converter: "Abrir o conversor", footer: "Guias práticos sobre formatos, qualidade e uso responsável de conteúdo público." },
  de: { nav: "Blog", home: "Startseite", title: "Video- und Audio-Ratgeber", subtitle: "Klare Erklärungen zu Formatwahl, Qualität und dem verantwortungsvollen Umgang mit öffentlichen Medien.", kicker: "Wissensbereich", latest: "Ausgewählte Ratgeber", read: "Ratgeber lesen", minRead: "Min. Lesezeit", published: "Veröffentlicht", updated: "Aktualisiert", contents: "In diesem Ratgeber", questions: "Häufige Fragen", related: "Weiterlesen", converter: "Konverter öffnen", footer: "Praxisnahe Ratgeber zu Formaten, Qualität und verantwortungsvoller Nutzung öffentlicher Inhalte." },
};

export const blogIndexGuides: Record<Locale, {
  title: string;
  intro: string;
  sections: { title: string; paragraphs: string[] }[];
}> = {
  fr: {
    title: "Comprendre avant de convertir",
    intro: "Cette bibliothèque réunit des repères concrets pour choisir un fichier adapté, reconnaître la qualité réellement disponible et résoudre les problèmes de lecture. Chaque guide distingue ce que la conversion peut préserver de ce qu’elle ne peut pas recréer.",
    sections: [
      { title: "Choisir un format selon l’usage", paragraphs: ["MP4 conserve l’image et reste le choix le plus compatible pour une vidéo. MP3 convient lorsque seul le son est nécessaire, tandis que M4A et Opus privilégient l’efficacité. WAV et FLAC servent plutôt au montage ou à l’archivage, avec des fichiers plus volumineux.", "Le bon choix dépend de l’appareil final, de l’espace disponible et du besoin de conserver l’image. Nos comparaisons expliquent aussi la différence entre un conteneur, un codec, une résolution et un débit afin d’éviter les extensions simplement renommées."] },
      { title: "Évaluer la qualité sans promesse artificielle", paragraphs: ["Une sortie 1080p n’est réellement détaillée que si la source publique propose cette résolution. De la même façon, encoder un son faible à 320 kbps augmente le débit du fichier sans restaurer les fréquences déjà perdues. Les guides montrent comment choisir une limite raisonnable plutôt que le nombre le plus élevé.", "Nous détaillons les profils H.264/AAC pour la compatibilité vidéo, les débits utiles pour la voix ou la musique et les contrôles effectués sur le fichier final. Vous pouvez ainsi comprendre pourquoi deux téléchargements portant la même extension ne se lisent pas toujours de la même manière."] },
      { title: "Télécharger de façon responsable et diagnostiquer une erreur", paragraphs: ["Les méthodes présentées concernent les médias publics que vous avez créés ou que vous êtes autorisé à conserver. Elles ne permettent pas d’ouvrir un compte privé, de contourner un abonnement ni de récupérer un contenu supprimé. Un lien qui fonctionne sans connexion est le meilleur point de départ.", "En cas d’échec, vérifiez l’URL de la publication originale, son statut public, la disponibilité du direct ou de la story et la lecture du fichier après conversion. Le guide de sécurité explique également comment reconnaître le vrai bouton de téléchargement et éviter les installations ou demandes d’identifiants inutiles."] },
    ],
  },
  en: {
    title: "Understand the file before you convert",
    intro: "This library provides practical guidance for choosing an appropriate file, judging the quality that is genuinely available and fixing common playback problems. Each guide separates what conversion can preserve from detail it cannot recreate.",
    sections: [
      { title: "Choose a format for the intended use", paragraphs: ["MP4 keeps the picture and is the most broadly compatible choice for video. MP3 is useful when only sound is needed, while M4A and Opus prioritize efficiency. WAV and FLAC are better suited to editing or archiving and usually create larger files.", "The right option depends on the target device, available storage and whether the picture matters. Our comparisons also explain containers, codecs, resolution and bitrate so that a renamed extension is never mistaken for a real conversion."] },
      { title: "Judge quality without inflated promises", paragraphs: ["A 1080p output contains true 1080p detail only when the public source supplies that resolution. Likewise, encoding weak audio at 320 kbps increases the output bitrate but cannot restore frequencies already lost. The guides help you select a sensible ceiling instead of automatically choosing the largest number.", "We cover H.264/AAC compatibility, useful bitrates for speech and music, and the final-file checks that identify the actual streams. This makes it easier to understand why two downloads with the same extension may behave differently on a phone, computer or television."] },
      { title: "Download responsibly and troubleshoot failures", paragraphs: ["The methods apply to public media you created or are permitted to keep. They do not unlock private accounts, bypass subscriptions or recover deleted posts. A source link that opens without signing in is the most reliable starting point.", "When a job fails, check the original post URL, public visibility, whether a live stream has ended and whether a story has expired. The safety guide also explains how to identify the real download control and avoid unnecessary software, notification prompts or requests for account credentials."] },
    ],
  },
  ar: {
    title: "افهم الملف قبل بدء التحويل",
    intro: "تجمع هذه المكتبة إرشادات عملية لاختيار الملف المناسب ومعرفة الجودة المتاحة فعلاً وحل مشكلات التشغيل الشائعة. يوضح كل دليل ما الذي يمكن للتحويل الحفاظ عليه وما لا يمكنه إعادة إنشائه.",
    sections: [
      { title: "اختر الصيغة حسب الاستخدام", paragraphs: ["تحافظ MP4 على الصورة وهي الأكثر توافقاً للفيديو، بينما تناسب MP3 من يريد الصوت فقط. توفر M4A وOpus كفاءة جيدة، أما WAV وFLAC فهما أنسب للتحرير أو الأرشفة وغالباً ينتجان ملفات أكبر.", "يعتمد الاختيار على الجهاز النهائي ومساحة التخزين والحاجة إلى الصورة. تشرح المقارنات أيضاً الفرق بين الحاوية والترميز والدقة ومعدل البيانات حتى لا يُعتبر تغيير امتداد الملف تحويلاً حقيقياً."] },
      { title: "قيّم الجودة بدون وعود مبالغ فيها", paragraphs: ["لا يحتوي ملف 1080p على تفاصيل حقيقية بهذه الدقة إلا إذا وفرها المصدر العام. كذلك لا يعيد ترميز صوت ضعيف إلى 320 kbps الترددات المفقودة، بل يزيد معدل بيانات الملف الناتج. تساعدك الأدلة على اختيار حد مناسب بدلاً من أعلى رقم تلقائياً.", "نشرح توافق H.264 وAAC، ومعدلات الصوت المناسبة للكلام والموسيقى، وفحص المسارات داخل الملف النهائي. وبذلك تعرف لماذا قد يختلف تشغيل ملفين لهما الامتداد نفسه على الهاتف أو الكمبيوتر أو التلفاز."] },
      { title: "نزّل بمسؤولية وحل الأخطاء", paragraphs: ["تنطبق الخطوات على الوسائط العامة التي أنشأتها أو لديك إذن بحفظها. لا تفتح حسابات خاصة ولا تتجاوز الاشتراكات ولا تستعيد منشوراً محذوفاً. الرابط الذي يعمل من دون تسجيل دخول هو أفضل نقطة بداية.", "عند فشل التحويل تحقق من رابط المنشور الأصلي ومن ظهوره للعامة ومن انتهاء البث المباشر أو صلاحية القصة. يوضح دليل الأمان أيضاً طريقة تمييز زر التنزيل الحقيقي وتجنب البرامج غير الضرورية أو طلبات الإشعارات وكلمات المرور."] },
    ],
  },
  es: {
    title: "Comprende el archivo antes de convertir",
    intro: "Esta biblioteca reúne criterios prácticos para elegir un archivo adecuado, valorar la calidad realmente disponible y resolver problemas de reproducción. Cada guía diferencia lo que una conversión puede conservar de lo que no puede reconstruir.",
    sections: [
      { title: "Elige el formato según el uso", paragraphs: ["MP4 conserva la imagen y ofrece amplia compatibilidad para vídeo. MP3 es apropiado cuando solo necesitas audio, mientras que M4A y Opus priorizan la eficiencia. WAV y FLAC se orientan más a edición o archivo y suelen ocupar más espacio.", "La mejor opción depende del dispositivo final, el almacenamiento y la necesidad de mantener la imagen. Las comparaciones explican contenedores, códecs, resolución y bitrate para no confundir una extensión renombrada con una conversión real."] },
      { title: "Valora la calidad sin promesas artificiales", paragraphs: ["Una salida 1080p solo contiene ese detalle si la fuente pública ofrece la resolución. Codificar un audio débil a 320 kbps tampoco recupera frecuencias perdidas: aumenta el bitrate de salida. Las guías ayudan a elegir un límite razonable en lugar de seleccionar siempre el número mayor.", "Explicamos la compatibilidad H.264/AAC, los bitrates útiles para voz o música y las comprobaciones de los flujos finales. Así puedes entender por qué dos descargas con la misma extensión no siempre se reproducen igual en móvil, ordenador o televisor."] },
      { title: "Descarga con responsabilidad y resuelve errores", paragraphs: ["Los métodos se aplican a contenido público que creaste o que tienes permiso para conservar. No desbloquean cuentas privadas, no eluden suscripciones ni recuperan publicaciones eliminadas. Un enlace que abre sin iniciar sesión es el mejor punto de partida.", "Si una conversión falla, comprueba la URL original, la visibilidad pública, si terminó el directo y si la historia sigue disponible. La guía de seguridad también ayuda a reconocer el control de descarga correcto y evitar programas, notificaciones o solicitudes de contraseña innecesarias."] },
    ],
  },
  pt: {
    title: "Entenda o arquivo antes de converter",
    intro: "Esta biblioteca reúne orientações práticas para escolher um arquivo adequado, avaliar a qualidade realmente disponível e corrigir problemas comuns de reprodução. Cada guia separa o que a conversão preserva do que ela não consegue recriar.",
    sections: [
      { title: "Escolha o formato conforme o uso", paragraphs: ["MP4 mantém a imagem e oferece ampla compatibilidade para vídeo. MP3 funciona quando apenas o áudio importa, enquanto M4A e Opus priorizam eficiência. WAV e FLAC são mais indicados para edição ou arquivo e normalmente ocupam mais espaço.", "A escolha depende do aparelho final, do armazenamento e da necessidade de manter a imagem. As comparações também explicam contêiner, codec, resolução e bitrate para não confundir uma extensão renomeada com uma conversão verdadeira."] },
      { title: "Avalie a qualidade sem promessas artificiais", paragraphs: ["Uma saída 1080p só contém esse nível de detalhe quando a fonte pública oferece a resolução. Codificar áudio fraco em 320 kbps também não recupera frequências perdidas; apenas aumenta o bitrate do arquivo. Os guias ajudam a definir um limite sensato em vez de sempre escolher o maior número.", "Explicamos a compatibilidade H.264/AAC, bitrates úteis para voz e música e a verificação dos fluxos do arquivo final. Isso esclarece por que dois downloads com a mesma extensão podem se comportar de forma diferente no celular, computador ou televisor."] },
      { title: "Baixe com responsabilidade e resolva falhas", paragraphs: ["Os métodos servem para mídia pública que você criou ou tem permissão para guardar. Eles não abrem contas privadas, não contornam assinaturas e não recuperam posts excluídos. Um link que abre sem login é o ponto de partida mais confiável.", "Se a conversão falhar, confira a URL original, a visibilidade pública, se a live terminou e se o story expirou. O guia de segurança também ensina a reconhecer o botão correto de download e evitar programas, notificações ou pedidos de senha desnecessários."] },
    ],
  },
  de: {
    title: "Die Datei vor der Konvertierung verstehen",
    intro: "Diese Bibliothek bietet praktische Orientierung für die Formatwahl, die real verfügbare Qualität und häufige Wiedergabeprobleme. Jeder Ratgeber trennt klar, was eine Konvertierung bewahren kann und welche Details sie nicht neu erzeugt.",
    sections: [
      { title: "Das Format nach dem Einsatzzweck wählen", paragraphs: ["MP4 bewahrt das Bild und ist für Videos besonders breit kompatibel. MP3 passt, wenn nur der Ton benötigt wird, während M4A und Opus auf Effizienz zielen. WAV und FLAC eignen sich eher für Bearbeitung oder Archivierung und erzeugen meist größere Dateien.", "Die richtige Wahl hängt vom Zielgerät, dem Speicherplatz und der Bedeutung des Bildes ab. Unsere Vergleiche erklären außerdem Container, Codec, Auflösung und Bitrate, damit eine umbenannte Dateiendung nicht mit einer echten Konvertierung verwechselt wird."] },
      { title: "Qualität ohne übertriebene Versprechen bewerten", paragraphs: ["Eine 1080p-Ausgabe enthält nur dann echte 1080p-Details, wenn die öffentliche Quelle diese Auflösung liefert. Schwaches Audio erhält durch 320 kbps keine verlorenen Frequenzen zurück; lediglich die Ausgabebitrate steigt. Die Ratgeber helfen, eine sinnvolle Grenze statt automatisch den höchsten Wert zu wählen.", "Wir erläutern H.264/AAC-Kompatibilität, passende Bitraten für Sprache und Musik sowie die Prüfung der tatsächlichen Streams. So wird verständlich, warum zwei Downloads mit derselben Endung auf Handy, Computer oder Fernseher unterschiedlich reagieren können."] },
      { title: "Verantwortungsvoll laden und Fehler eingrenzen", paragraphs: ["Die Methoden gelten für öffentliche Medien, die du selbst erstellt hast oder speichern darfst. Sie öffnen keine privaten Konten, umgehen keine Abos und stellen keine gelöschten Beiträge wieder her. Ein Link, der ohne Anmeldung funktioniert, ist der zuverlässigste Ausgangspunkt.", "Scheitert ein Auftrag, prüfe die Original-URL, die öffentliche Sichtbarkeit, das Ende eines Livestreams und den Ablauf einer Story. Der Sicherheitsratgeber zeigt außerdem, wie du die echte Download-Funktion erkennst und unnötige Programme, Benachrichtigungen oder Passwortabfragen vermeidest."] },
    ],
  },
};

export const blogPosts: Record<Locale, Record<BlogPostId, BlogPost>> = {
  fr: {
    "formats-guide": {
      id: "formats-guide", slug: "mp4-mp3-quel-format-choisir",
      title: "MP4, MP3, M4A, WAV, FLAC ou OPUS : quel format choisir ?",
      description: "Comparez MP4, MP3, M4A, WAV, FLAC et OPUS pour choisir le bon format, la bonne résolution et le bon débit selon votre appareil.",
      eyebrow: "Guide des formats", readTime: "11", published: "2026-08-24", updated: "2026-08-24",
      keywords: ["MP4 ou MP3", "quel format vidéo choisir", "M4A ou MP3", "WAV ou FLAC", "qualité vidéo 1080p", "bitrate MP3 320 kbps"],
      intro: [
        "Choisir un format ne consiste pas seulement à sélectionner une extension de fichier. Il faut décider si vous avez besoin de l’image, déterminer les appareils sur lesquels le média sera lu, évaluer l’espace disponible et tenir compte de la qualité réelle de la source. Une vidéo publique en 720p ne devient pas plus détaillée parce qu’elle est exportée avec une limite de 1080p, tout comme un son déjà compressé ne récupère pas ses détails en passant dans un fichier 320 kbps.",
        "Ce guide distingue les conteneurs, les codecs, la résolution et le débit. Il vous aide à choisir entre MP4 pour la vidéo et MP3, M4A, WAV, AAC, FLAC ou OPUS pour l’audio, sans promesse artificielle. L’objectif est simple : obtenir un fichier adapté à son usage, compatible avec l’appareil cible et aussi fidèle que la source le permet.",
      ],
      sections: [
        { id: "conteneur-codec", title: "Conteneur, codec et extension : trois notions différentes", paragraphs: [
          "L’extension visible à la fin du nom indique généralement un conteneur ou un format de fichier. MP4 est un conteneur capable de réunir une piste vidéo, une piste audio, des sous-titres et des métadonnées. À l’intérieur, la vidéo peut être encodée en H.264 et l’audio en AAC. Deux fichiers .mp4 peuvent donc utiliser des composants différents et ne pas présenter exactement la même compatibilité.",
          "Un codec décrit la manière dont l’image ou le son est compressé. H.264 et AAC sont largement lus par les navigateurs, téléphones et téléviseurs. MP3, FLAC et Opus sont des codecs audio avec des objectifs différents. Renommer simplement une extension ne convertit rien : une vraie conversion doit produire le flux attendu, puis vérifier le fichier final.",
        ] },
        { id: "mp4-video", title: "Choisir MP4 lorsque l’image compte", paragraphs: [
          "MP4 est le choix le plus simple pour conserver la vidéo. Un fichier associant H.264 pour l’image et AAC pour le son fonctionne généralement sur iPhone, Android, Windows, macOS, téléviseurs et logiciels de présentation. Il convient aux tutoriels, démonstrations, archives personnelles autorisées et contenus destinés à être relus hors connexion.",
          "Sélectionnez la résolution selon l’écran et la source. 360p réduit fortement la taille, 480p reste utile sur un petit écran, 720p offre un bon compromis mobile et 1080p préserve davantage de détails. La mention « jusqu’à 1080p » est importante : si la plateforme ne fournit que 720p, le résultat correct reste 720p. Agrandir l’image créerait des pixels interpolés, pas de vrais détails.",
        ], bullets: ["360p : priorité aux petits fichiers et connexions lentes", "720p : bon équilibre pour téléphone et tablette", "1080p : écrans plus grands lorsque la source le propose réellement"] },
        { id: "audio-formats", title: "MP3, M4A, AAC, WAV, FLAC et OPUS : les différences utiles", paragraphs: [
          "MP3 reste le format le plus universel pour la musique, la voix, les autoradios et les anciens lecteurs. M4A contient souvent de l’audio AAC et peut offrir une bonne efficacité à débit comparable, notamment dans les écosystèmes mobiles. AAC seul est utile lorsque le logiciel cible attend ce flux. Opus est très efficace pour la voix et le streaming moderne, mais certains appareils anciens le reconnaissent moins bien.",
          "WAV est souvent non compressé et produit des fichiers volumineux, adaptés au montage ou à un traitement intermédiaire. FLAC compresse sans perte : après décompression, les données audio restent identiques à celles du flux fourni au format FLAC. Toutefois, convertir une source déjà compressée en WAV ou FLAC n’en restaure pas les informations perdues ; cela évite seulement une nouvelle perte lors des étapes suivantes.",
        ], bullets: ["MP3 : compatibilité maximale", "M4A/AAC : bonne efficacité sur appareils récents", "WAV : montage et traitement, fichiers volumineux", "FLAC : archivage sans perte supplémentaire", "OPUS : excellente efficacité, compatibilité à vérifier"] },
        { id: "bitrate", title: "Comprendre le débit audio sans tomber dans le piège du 320 kbps", paragraphs: [
          "Le débit indique la quantité approximative de données utilisée chaque seconde pour un format compressé. Pour de la parole, 128 ou 192 kbps peut suffire. Pour la musique, 256 ou 320 kbps limite davantage les pertes ajoutées par un nouvel encodage. Le meilleur choix dépend de la source, du casque, de l’environnement d’écoute et de l’espace disponible.",
          "Un export MP3 à 320 kbps ne garantit pas que la source contenait cette qualité. Si le son d’origine a déjà été fortement compressé, augmenter le débit de sortie augmente surtout la taille du fichier. Un convertisseur transparent doit annoncer le débit cible, pas prétendre reconstruire des fréquences ou des détails absents.",
        ] },
        { id: "choix-appareil", title: "Le meilleur choix selon votre appareil et votre usage", paragraphs: [
          "Pour partager une vidéo entre plusieurs appareils, MP4 H.264/AAC reste la valeur sûre. Pour écouter dans une voiture, sur une clé USB ou un lecteur ancien, choisissez MP3. Pour un iPhone ou une bibliothèque moderne, M4A constitue une alternative compacte. Pour le montage, WAV évite une étape de décompression complexe ; pour l’archivage d’une source réellement sans perte, FLAC économise de l’espace par rapport au WAV.",
          "Avant de lancer une conversion, vérifiez quatre points : faut-il conserver l’image, quel appareil lira le fichier, quelle qualité la source offre réellement et combien d’espace pouvez-vous utiliser ? Cette courte vérification évite les fichiers incompatibles, les tailles inutiles et les attentes irréalistes.",
        ] },
        { id: "verification", title: "Comment reconnaître un fichier correctement converti", paragraphs: [
          "Un téléchargement terminé n’est pas toujours une conversion réussie. Le fichier doit s’ouvrir, contenir la piste attendue, afficher une durée cohérente et utiliser un codec compatible. Pour une vidéo MP4, l’association H.264, AAC et yuv420p offre une large compatibilité. Pour un fichier audio, il ne doit rester aucune piste vidéo et le codec doit correspondre à l’extension annoncée.",
          "toTube utilise FFmpeg pour préparer le média et FFprobe pour examiner le résultat avant de proposer le téléchargement. Cette vérification ne peut pas améliorer une mauvaise source, mais elle évite de présenter comme MP3 ou MP4 un fichier mal encodé, incomplet ou simplement renommé.",
        ] },
      ],
      faqs: [
        { question: "MP4 ou MP3 : lequel choisir ?", answer: "Choisissez MP4 si vous voulez conserver l’image. Choisissez MP3 si seul le son vous intéresse et que vous recherchez la compatibilité la plus large." },
        { question: "Un MP3 320 kbps est-il toujours de meilleure qualité ?", answer: "Non. Il réduit les pertes du nouvel encodage, mais la qualité finale reste limitée par le son de la source." },
        { question: "FLAC est-il meilleur que WAV ?", answer: "Les deux peuvent conserver le son sans perte. FLAC compresse les données et occupe généralement moins d’espace ; WAV est souvent préféré dans certains flux de montage." },
        { question: "Pourquoi une vidéo 1080p peut-elle sortir en 720p ?", answer: "Parce que le convertisseur respecte la meilleure résolution réellement fournie par la source au lieu d’inventer des détails par agrandissement." },
      ],
      ctaTitle: "Choisissez votre format avec une qualité transparente", ctaText: "Collez un lien public, choisissez MP4 ou un format audio, puis sélectionnez la résolution ou le débit adapté.", ctaLabel: "Convertir un média public",
    },
    "safe-download-guide": {
      id: "safe-download-guide", slug: "telecharger-video-en-ligne-guide-securite",
      title: "Télécharger une vidéo en ligne : méthode, qualité et sécurité",
      description: "Guide complet pour télécharger une vidéo publique autorisée, choisir la qualité, éviter les faux boutons et résoudre les erreurs courantes.",
      eyebrow: "Guide pratique", readTime: "12", published: "2026-08-24", updated: "2026-08-24",
      keywords: ["télécharger vidéo en ligne", "télécharger vidéo sans logiciel", "téléchargeur vidéo sécurisé", "télécharger vidéo sur iPhone", "télécharger vidéo Android"],
      intro: [
        "Télécharger une vidéo en ligne paraît simple : copier une adresse, choisir un format et enregistrer le fichier. En pratique, la réussite dépend du type de lien, de la visibilité du contenu, de la qualité réellement proposée par la plateforme et de la compatibilité du fichier final. La sécurité compte également, car les pages trompeuses, faux boutons et demandes d’installation inutiles sont fréquents sur le Web.",
        "Cette méthode s’applique aux contenus publics que vous avez créés ou que vous êtes autorisé à conserver. Elle ne sert pas à contourner un compte privé, un abonnement, une restriction d’accès ou une mesure de protection. Vous apprendrez à récupérer le bon lien, choisir un format raisonnable, contrôler le téléchargement et diagnostiquer une conversion qui échoue.",
      ],
      sections: [
        { id: "autorisation", title: "Commencer par l’accès public et l’autorisation", paragraphs: [
          "Un contenu visible publiquement n’est pas automatiquement libre de droits. Avant de le télécharger, vérifiez que vous en êtes l’auteur, que le créateur a donné son autorisation, qu’une licence le permet ou que votre usage est autorisé par la loi applicable. Les conditions de la plateforme peuvent également encadrer la copie ou l’usage hors ligne.",
          "Un outil responsable ne demande pas vos identifiants et ne promet pas d’ouvrir les comptes privés. Les publications réservées aux amis, groupes fermés, stories expirées, vidéos payantes et contenus supprimés doivent rester inaccessibles. Cette limite protège à la fois la confidentialité des utilisateurs et votre propre compte.",
        ] },
        { id: "bon-lien", title: "Copier le bon lien sur YouTube, TikTok, Instagram, Facebook, X, Rumble ou Threads", paragraphs: [
          "Utilisez le bouton de partage de la publication originale plutôt que l’adresse d’une page de recherche ou d’un lecteur intégré. Sur YouTube, une URL de vidéo ou de Short public convient ; une playlist peut nécessiter le traitement d’une vidéo à la fois. Sur TikTok, Instagram et Threads, ouvrez la publication elle-même. Sur Facebook, assurez-vous qu’elle reste visible dans une fenêtre privée sans connexion.",
          "Sur X, les animations appelées GIF sont souvent diffusées comme de petites vidéos MP4. Sur Rumble, attendez la fin d’un direct avant de traiter la version publiée. Un lien raccourci peut fonctionner, mais l’URL finale de la publication est plus facile à diagnostiquer. Si la page exige une connexion, le convertisseur public ne doit pas essayer de la contourner.",
        ], bullets: ["Ouvrir la publication originale", "Utiliser Partager puis Copier le lien", "Vérifier que le lien fonctionne sans connexion", "Éviter les pages de recherche et les profils privés"] },
        { id: "format-qualite", title: "Choisir le format et la qualité sans gonfler inutilement le fichier", paragraphs: [
          "Gardez MP4 si l’image est utile. Choisissez MP3 ou M4A pour une écoute simple, WAV pour certains travaux de montage, FLAC pour éviter une perte supplémentaire avec une source adaptée, ou Opus lorsqu’une excellente efficacité est prioritaire. Le format doit être déterminé par l’usage final, pas par le nombre le plus élevé affiché.",
          "Pour la vidéo, 720p suffit souvent sur téléphone tandis que 1080p convient à un écran plus grand lorsque la source le fournit. Pour l’audio compressé, 128 ou 192 kbps est souvent adapté à la parole ; 256 ou 320 kbps peut être choisi pour la musique. Aucune conversion ne recrée les détails absents du média original.",
        ] },
        { id: "securite", title: "Reconnaître un téléchargement sûr", paragraphs: [
          "Un convertisseur en ligne ne devrait pas vous demander d’installer une extension, un lecteur spécial ou une application inconnue pour récupérer un fichier standard. Vérifiez l’adresse du site, la présence de HTTPS et le nom du fichier avant de l’ouvrir. Refusez les notifications non nécessaires et ne saisissez jamais votre mot de passe de réseau social dans un convertisseur tiers.",
          "La publicité doit être identifiable comme telle. Un bouton de téléchargement légitime apparaît après la conversion et indique le fichier préparé ; une bannière qui promet un prix, une alerte système ou une mise à jour urgente n’est pas le résultat. Sur mobile, consultez ensuite le dossier Téléchargements ou l’application Fichiers et analysez tout fichier dont l’extension paraît inhabituelle.",
        ] },
        { id: "depannage", title: "Pourquoi une conversion échoue et quoi vérifier", paragraphs: [
          "Une erreur peut provenir d’un lien privé, supprimé, régional, en direct ou temporairement limité par la plateforme. Elle peut aussi venir d’un changement technique du site source, d’un serveur saturé, d’un proxy indisponible ou d’un fichier trop long. Réessayez avec l’URL originale, confirmez qu’elle se lit sans connexion et patientez si la plateforme limite temporairement les requêtes.",
          "Si YouTube demande de confirmer que vous n’êtes pas un robot, multiplier immédiatement les tentatives peut aggraver le blocage. Un service peut essayer une autre route réseau, mais il ne peut garantir l’accès à chaque vidéo. Lorsque vous possédez déjà le fichier, le téléversement direct est souvent la méthode la plus fiable pour changer son format sans dépendre de la plateforme.",
        ], bullets: ["Tester le lien dans une fenêtre privée", "Retirer les paramètres inutiles après le point d’interrogation", "Essayer une qualité inférieure si le flux HD manque", "Téléverser votre propre fichier lorsque la plateforme bloque le lien"] },
        { id: "apres", title: "Après le téléchargement : vérifier, nommer et protéger le fichier", paragraphs: [
          "Ouvrez le média dans le lecteur habituel et contrôlez le début, le milieu et la fin. Vérifiez la durée, le son, l’image et le décalage éventuel entre les pistes. Un fichier qui porte l’extension .mp4 mais ne s’ouvre pas peut être incomplet ou utiliser un codec non compatible ; une vérification serveur avec FFprobe réduit ce risque.",
          "Renommez le fichier avec un titre clair, la date et, si nécessaire, le nom du créateur. Conservez les informations de licence ou d’autorisation avec votre archive. Supprimez les copies temporaires inutiles et évitez de republier le contenu comme s’il vous appartenait. Une bonne organisation rend le fichier plus facile à retrouver tout en préservant son contexte.",
        ] },
      ],
      faqs: [
        { question: "Puis-je télécharger une vidéo privée ?", answer: "Non. Un convertisseur public ne doit pas contourner une connexion, un compte privé, un abonnement ou une restriction d’accès." },
        { question: "Quel format fonctionne sur iPhone et Android ?", answer: "MP4 avec vidéo H.264 et audio AAC offre une large compatibilité. Pour l’audio seul, MP3 et M4A sont de bons choix." },
        { question: "Pourquoi le téléchargement ne démarre-t-il pas ?", answer: "Le lien peut être inaccessible, la conversion encore en cours ou le navigateur peut bloquer une fenêtre. Vérifiez le résultat affiché et autorisez uniquement le téléchargement attendu." },
        { question: "Un convertisseur doit-il demander mon mot de passe ?", answer: "Non. Ne communiquez jamais vos identifiants de plateforme à un convertisseur tiers." },
      ],
      ctaTitle: "Prêt à convertir un contenu public autorisé ?", ctaText: "Utilisez le lien original, sélectionnez une qualité réaliste et vérifiez le fichier final avant de le conserver.", ctaLabel: "Essayer toTube",
    },
  },
  en: {
    "formats-guide": {
      id: "formats-guide", slug: "mp4-mp3-best-video-audio-format", title: "MP4, MP3, M4A, WAV, FLAC or Opus: which format should you choose?", description: "Compare MP4, MP3, M4A, WAV, FLAC and Opus to choose the right format, resolution and bitrate for any device.", eyebrow: "Format guide", readTime: "11", published: "2026-08-24", updated: "2026-08-24", keywords: ["MP4 vs MP3", "best video format", "M4A vs MP3", "WAV vs FLAC", "1080p video quality", "MP3 320 kbps"],
      intro: ["Choosing a format is not just choosing a filename extension. You need to decide whether the picture matters, identify the devices that will play the file, consider available storage and respect the quality of the source. A public 720p stream does not gain real detail when exported with a 1080p ceiling, and heavily compressed audio does not recover missing information inside a 320 kbps file.", "This guide separates containers, codecs, resolution and bitrate. It explains when MP4 is the practical video choice and how MP3, M4A, AAC, WAV, FLAC and Opus differ for audio. The aim is a file that fits the job, plays on the target device and remains as faithful as the available source allows."],
      sections: [
        { id: "container-codec", title: "Container, codec and extension are not the same thing", paragraphs: ["The visible extension usually names a container or file format. MP4 is a container that can hold video, audio, subtitles and metadata. Inside it, H.264 may encode the picture while AAC encodes the sound. Two .mp4 files can therefore contain different components and behave differently on the same device.", "A codec describes how picture or sound data is compressed. H.264 and AAC enjoy broad support in browsers, phones and televisions. MP3, FLAC and Opus are audio codecs with different goals. Renaming an extension performs no conversion; a genuine converter must create the expected stream and inspect the finished file."] },
        { id: "mp4-video", title: "Choose MP4 when the picture matters", paragraphs: ["MP4 is the straightforward choice for retaining video. H.264 video with AAC audio generally plays on iPhone, Android, Windows, macOS, televisions and presentation software. It suits tutorials, demonstrations, authorized personal archives and media intended for offline playback.", "Match resolution to the screen and source. 360p keeps files small, 480p can work on compact displays, 720p is a useful mobile balance and 1080p preserves more detail. The phrase ‘up to 1080p’ matters: if the platform only exposes 720p, a correct result stays at 720p. Upscaling creates interpolated pixels, not missing detail."], bullets: ["360p: smaller files and slower connections", "720p: balanced quality for phones and tablets", "1080p: larger screens when the source genuinely provides it"] },
        { id: "audio-formats", title: "The useful differences between MP3, M4A, AAC, WAV, FLAC and Opus", paragraphs: ["MP3 remains the broadest choice for music, speech, car stereos and older players. M4A often contains AAC audio and can be efficient on modern mobile devices. Standalone AAC is useful when a workflow specifically expects that stream. Opus is highly efficient for speech and modern streaming, although some older hardware offers weaker support.", "WAV commonly stores uncompressed audio and creates large files suited to editing or intermediate work. FLAC compresses without losing audio data: decoding recreates the data supplied to the FLAC encoder. Converting an already compressed source to WAV or FLAC cannot restore information that has already disappeared; it merely prevents another lossy stage later."] , bullets: ["MP3: maximum compatibility", "M4A/AAC: efficient on modern devices", "WAV: editing with large files", "FLAC: lossless storage", "Opus: excellent efficiency; verify device support"] },
        { id: "bitrate", title: "Understand bitrate without falling for the 320 kbps trap", paragraphs: ["Bitrate is the approximate amount of data used each second by a compressed format. Speech may sound appropriate at 128 or 192 kbps. For music, 256 or 320 kbps can reduce additional encoding loss. The sensible choice depends on the source, headphones, listening environment and storage budget.", "A 320 kbps MP3 export does not prove that the source contained equivalent quality. If the original sound was already heavily compressed, a higher output bitrate mainly increases file size. A transparent converter states the encoding target rather than claiming to rebuild frequencies and detail that are absent."] },
        { id: "device-choice", title: "The best choice for common devices and jobs", paragraphs: ["For video shared across devices, MP4 with H.264/AAC is the safe default. For a car, USB drive or older player, use MP3. M4A is compact for modern phone libraries. WAV is practical in some editing workflows, while FLAC saves space when archiving a source that genuinely warrants lossless storage.", "Before converting, ask four questions: must I keep the picture, which device will play the file, what quality does the source really offer and how much storage can I spend? This quick check prevents incompatible files, unnecessary size and unrealistic expectations."] },
        { id: "verification", title: "How to recognize a correctly converted file", paragraphs: ["A completed download is not automatically a successful conversion. The file should open, contain the expected tracks, show a plausible duration and use supported codecs. For MP4, H.264, AAC and yuv420p provide broad compatibility. For audio output, no video track should remain and the codec should match the advertised extension.", "toTube uses FFmpeg to prepare media and FFprobe to inspect the output before presenting it. Verification cannot repair a poor source, but it helps prevent a renamed, truncated or incorrectly encoded file from being presented as a working MP3 or MP4."] },
      ],
      faqs: [{ question: "Should I choose MP4 or MP3?", answer: "Choose MP4 to keep the picture. Choose MP3 when you only need audio and want the broadest playback support." }, { question: "Is 320 kbps MP3 always better?", answer: "No. It can reduce loss from the new encode, but the source still limits the final sound." }, { question: "Is FLAC better than WAV?", answer: "Both can preserve audio losslessly. FLAC compresses the data and usually uses less space; WAV remains convenient in some editing workflows." }, { question: "Why can a 1080p selection produce 720p?", answer: "Because the converter respects the best resolution actually available instead of inventing detail by upscaling." }],
      ctaTitle: "Choose a format with transparent quality", ctaText: "Paste a public link, select MP4 or an audio format, then choose a resolution or bitrate that fits the source.", ctaLabel: "Convert public media",
    },
    "safe-download-guide": {
      id: "safe-download-guide", slug: "download-video-online-safely", title: "How to download video online safely: quality, formats and troubleshooting", description: "A complete guide to downloading authorized public video, choosing quality, avoiding fake buttons and solving common conversion errors.", eyebrow: "Practical guide", readTime: "12", published: "2026-08-24", updated: "2026-08-24", keywords: ["download video online", "download video without software", "safe video downloader", "download video on iPhone", "download video on Android"],
      intro: ["Downloading online video sounds simple: copy an address, select a format and save a file. In practice, success depends on the kind of link, whether the media is public, the quality actually supplied by the platform and the compatibility of the final output. Security matters too because misleading pages, fake download buttons and unnecessary installation prompts are common across the web.", "This workflow is for public media you created or are authorized to keep. It is not a method for bypassing a private account, subscription, access restriction or technical protection. You will learn how to copy the correct link, select a sensible format, check the download and diagnose a conversion that does not work."],
      sections: [
        { id: "permission", title: "Start with public access and permission", paragraphs: ["Publicly visible does not automatically mean copyright-free. Before downloading, confirm that you created the media, the creator granted permission, a license allows the use or your intended use is lawful where you live. A platform’s terms may also regulate copying and offline use.", "A responsible tool does not request social-media credentials or promise access to private accounts. Friends-only posts, closed groups, expired stories, paid videos and removed media should remain inaccessible. That boundary protects user privacy as well as your own account."] },
        { id: "correct-link", title: "Copy the correct link from YouTube, TikTok, Instagram, Facebook, X, Rumble or Threads", paragraphs: ["Use the share control on the original post instead of copying a search page or embedded player. A public YouTube video or Short URL is appropriate; playlist links may need one item at a time. On TikTok, Instagram and Threads, open the actual post. For Facebook, verify that it remains visible in a private browser window without signing in.", "X frequently delivers animated GIF posts as compact MP4 video. On Rumble, wait for a live event to finish and use the published replay. Short links may work, but the final post URL is easier to diagnose. If the page itself requires a login, a public converter should not attempt to bypass it."], bullets: ["Open the original post", "Use Share and Copy link", "Check that the page works without signing in", "Avoid search pages and private profiles"] },
        { id: "format-quality", title: "Choose format and quality without inflating the file", paragraphs: ["Keep MP4 when you need the picture. Choose MP3 or M4A for straightforward listening, WAV for selected editing jobs, FLAC to avoid another lossy stage with a suitable source, or Opus when efficiency matters. The final use should determine the format, not the largest number in the menu.", "For video, 720p is often enough on a phone; 1080p suits a larger display when the source provides it. For compressed audio, 128 or 192 kbps can suit speech, while 256 or 320 kbps may be appropriate for music. Conversion cannot recreate details absent from the original stream."] },
        { id: "security", title: "Recognize a safe download flow", paragraphs: ["An online converter should not require an unknown extension, special player or unrelated application to deliver a standard media file. Check the domain, HTTPS connection and filename before opening it. Decline unnecessary notification requests and never enter a social-media password into a third-party converter.", "Advertising should be identifiable. The legitimate download control appears after conversion and refers to the prepared file; a banner promising a prize, system warning or urgent update is not your result. On mobile, review the Downloads folder or Files app and treat any unexpected extension with caution."] },
        { id: "troubleshooting", title: "Why conversion fails and what to check", paragraphs: ["A failure can result from private, deleted, region-limited or live media. The source platform may have changed technically, the service can be busy, a network route may be unavailable or the item may exceed a service limit. Retry with the original URL, confirm it plays without a login and wait when the platform is temporarily rate-limiting requests.", "When YouTube asks to confirm that a request is not automated, immediately repeating many requests can deepen the block. A service may try another network route, but it cannot guarantee every video. If you already own the file, direct upload is usually the most reliable way to change its format without depending on the source platform."], bullets: ["Test the URL in a private window", "Remove unnecessary tracking parameters", "Try a lower ceiling if the HD stream is unavailable", "Upload your own file when link access is blocked"] },
        { id: "after-download", title: "After downloading: verify, name and protect the file", paragraphs: ["Play the beginning, middle and end in your normal media player. Check duration, sound, picture and synchronization. A .mp4 file that does not open may be incomplete or use an unsupported codec; server-side inspection with FFprobe reduces that risk.", "Rename the file with a clear title, date and creator when useful. Keep license or permission information beside your archive. Remove unneeded temporary copies and do not republish media as if it were your own. Good organization preserves context and makes the file easier to find later."] },
      ],
      faqs: [{ question: "Can I download a private video?", answer: "No. A public converter should not bypass a login, private account, subscription or access restriction." }, { question: "Which format works on iPhone and Android?", answer: "MP4 with H.264 video and AAC audio offers broad support. MP3 and M4A are practical for audio-only files." }, { question: "Why does the download not start?", answer: "The link may be inaccessible, conversion may still be running or the browser may block a window. Use only the result control shown after completion." }, { question: "Should a converter ask for my password?", answer: "No. Never give platform credentials to a third-party converter." }],
      ctaTitle: "Ready to convert authorized public media?", ctaText: "Use the original post URL, choose realistic quality and verify the result before keeping it.", ctaLabel: "Try toTube",
    },
  },
  ar: {
    "formats-guide": {
      id: "formats-guide", slug: "dalil-ikhtiyar-sighat-video-audio", title: "MP4 أم MP3 أم M4A أم WAV أم FLAC أم OPUS: أي صيغة تختار؟", description: "مقارنة عملية بين صيغ MP4 وMP3 وM4A وWAV وFLAC وOPUS لاختيار الجودة والدقة ومعدل الصوت المناسب.", eyebrow: "دليل الصيغ", readTime: "11", published: "2026-08-24", updated: "2026-08-24", keywords: ["MP4 أو MP3", "أفضل صيغة فيديو", "M4A أو MP3", "WAV أو FLAC", "جودة 1080p", "MP3 320 kbps"],
      intro: ["اختيار الصيغة لا يعني اختيار امتداد الملف فقط. عليك تحديد ما إذا كنت تحتاج إلى الصورة، ومعرفة الأجهزة التي ستشغّل الملف، وحساب مساحة التخزين، واحترام جودة المصدر. البث العام بدقة 720p لا يكتسب تفاصيل حقيقية عند تصديره بحد 1080p، والصوت المضغوط لا يستعيد المعلومات المفقودة داخل ملف 320 kbps.", "يفصل هذا الدليل بين الحاوية والترميز والدقة ومعدل البيانات. يشرح متى يكون MP4 مناسباً للفيديو، وما الفرق العملي بين MP3 وM4A وAAC وWAV وFLAC وOpus. الهدف هو ملف يناسب الاستخدام ويعمل على الجهاز ويحافظ على أقصى ما يتيحه المصدر."],
      sections: [
        { id: "container-codec", title: "الحاوية والترميز والامتداد ليست شيئاً واحداً", paragraphs: ["يدل الامتداد غالباً على الحاوية أو نوع الملف. حاوية MP4 قد تجمع الفيديو والصوت والترجمة والبيانات الوصفية. يمكن أن تكون الصورة بترميز H.264 والصوت بترميز AAC، لذلك قد يختلف ملفان بالامتداد نفسه في التوافق.", "الترميز يحدد طريقة ضغط الصورة أو الصوت. ينتشر دعم H.264 وAAC في المتصفحات والهواتف والتلفاز، بينما تخدم MP3 وFLAC وOpus أهدافاً مختلفة. تغيير اسم الامتداد لا يحول الملف؛ التحويل الحقيقي ينشئ المسار المطلوب ثم يفحص النتيجة."] },
        { id: "mp4-video", title: "اختر MP4 عندما تحتاج إلى الصورة", paragraphs: ["يعد MP4 الخيار الأبسط للاحتفاظ بالفيديو. تعمل تركيبة H.264 للصورة وAAC للصوت عادة على iPhone وAndroid وWindows وmacOS والتلفاز. وهي مناسبة للشروحات والعروض والأرشيف الشخصي المسموح به.", "اختر الدقة حسب الشاشة والمصدر. تقلل 360p حجم الملف، وتناسب 720p معظم الهواتف، وتحافظ 1080p على تفاصيل أكثر عندما يوفرها المصدر فعلاً. إذا كانت أفضل نسخة عامة 720p فالنتيجة الصحيحة تبقى 720p؛ التكبير لا يصنع تفاصيل حقيقية."], bullets: ["360p للملفات الصغيرة والاتصال البطيء", "720p توازن جيد للهاتف والجهاز اللوحي", "1080p للشاشات الأكبر عندما يتيحها المصدر"] },
        { id: "audio-formats", title: "الفروق العملية بين صيغ الصوت", paragraphs: ["تقدم MP3 أوسع توافق مع السيارات والمشغلات القديمة. تحتوي M4A غالباً على AAC وتوفر كفاءة جيدة في الأجهزة الحديثة. يناسب Opus الصوت والبث الحديث بكفاءة مرتفعة، لكن بعض الأجهزة القديمة لا تدعمه جيداً.", "يكون WAV غالباً غير مضغوط ولذلك حجمه كبير ومفيد في التحرير. يضغط FLAC بدون فقدان للبيانات التي دخلت إلى عملية الترميز. لكن تحويل مصدر مضغوط مسبقاً إلى WAV أو FLAC لا يعيد المعلومات المفقودة؛ بل يمنع فقداناً إضافياً في الخطوات التالية."], bullets: ["MP3 لأوسع توافق", "M4A/AAC لكفاءة جيدة", "WAV للتحرير وحجمه كبير", "FLAC للحفظ بدون فقدان إضافي", "Opus لكفاءة مرتفعة مع فحص التوافق"] },
        { id: "bitrate", title: "فهم معدل الصوت 320 kbps بدون مبالغة", paragraphs: ["يشير معدل البيانات إلى كمية البيانات المستخدمة كل ثانية تقريباً. قد تكفي 128 أو 192 kbps للكلام، بينما تقلل 256 أو 320 kbps خسائر الترميز الإضافية في الموسيقى. يعتمد الاختيار على المصدر وسماعاتك ومساحة التخزين.", "لا يثبت ملف MP3 بمعدل 320 kbps أن المصدر احتوى الجودة نفسها. إذا كان الصوت الأصلي مضغوطاً بشدة، فإن زيادة المعدل تكبر الملف أكثر مما تحسن الصوت. الشفافية تعني إعلان معدل الخرج من دون ادعاء استعادة تفاصيل غائبة."] },
        { id: "device-choice", title: "الاختيار المناسب للجهاز والاستخدام", paragraphs: ["للفيديو بين أجهزة متعددة اختر MP4 بترميز H.264/AAC. للسيارة أو USB أو مشغل قديم اختر MP3. توفر M4A خياراً مدمجاً للهواتف الحديثة، بينما يفيد WAV في بعض برامج التحرير وFLAC في الأرشفة بدون فقدان إضافي.", "اسأل قبل التحويل: هل أحتاج الصورة؟ ما الجهاز الذي سيشغّل الملف؟ ما الجودة التي يوفرها المصدر؟ وكم مساحة أستطيع استخدامه؟ تمنع هذه الأسئلة ملفات غير متوافقة وأحجاماً غير ضرورية."] },
        { id: "verification", title: "كيف تعرف أن الملف حُوّل بشكل صحيح؟", paragraphs: ["يجب أن يفتح الملف ويحتوي على المسارات المتوقعة ومدة منطقية وترميزات متوافقة. يوفر H.264 مع AAC وyuv420p توافقاً واسعاً في MP4. أما ملف الصوت فيجب ألا يحتوي على مسار فيديو وأن يطابق الترميز الامتداد المعلن.", "يستخدم toTube برنامج FFmpeg لإعداد الوسائط وFFprobe لفحص النتيجة. لا يصلح الفحص مصدراً ضعيفاً، لكنه يمنع تقديم ملف ناقص أو أعيدت تسميته فقط على أنه MP3 أو MP4 سليم."] },
      ],
      faqs: [{ question: "هل أختار MP4 أم MP3؟", answer: "اختر MP4 للاحتفاظ بالصورة، وMP3 إذا كنت تحتاج إلى الصوت فقط وأوسع توافق." }, { question: "هل 320 kbps أفضل دائماً؟", answer: "لا، فالنتيجة محدودة بجودة المصدر حتى مع تقليل خسائر الترميز الجديد." }, { question: "هل FLAC أفضل من WAV؟", answer: "كلاهما قد يحفظ الصوت بدون فقدان. يضغط FLAC البيانات ويوفر مساحة، بينما يناسب WAV بعض برامج التحرير." }, { question: "لماذا تخرج 720p عند اختيار 1080p؟", answer: "لأن المحول يحترم أفضل دقة متاحة فعلاً ولا يخترع تفاصيل بالتكبير." }],
      ctaTitle: "اختر الصيغة بجودة واضحة", ctaText: "ألصق رابطاً عاماً واختر MP4 أو صيغة صوتية ثم حدد دقة أو معدلاً يناسب المصدر.", ctaLabel: "تحويل محتوى عام",
    },
    "safe-download-guide": {
      id: "safe-download-guide", slug: "tanzil-video-online-bi-aman", title: "كيفية تنزيل فيديو عبر الإنترنت بأمان وجودة مناسبة", description: "دليل لتنزيل فيديو عام مصرح به واختيار الجودة وتجنب الأزرار المضللة وحل أخطاء التحويل الشائعة.", eyebrow: "دليل عملي", readTime: "12", published: "2026-08-24", updated: "2026-08-24", keywords: ["تنزيل فيديو اون لاين", "تنزيل فيديو بدون برنامج", "تنزيل فيديو آمن", "تنزيل فيديو للايفون", "تنزيل فيديو للاندرويد"],
      intro: ["يبدو تنزيل الفيديو بسيطاً: نسخ الرابط واختيار الصيغة وحفظ الملف. لكن النجاح يعتمد على نوع الرابط وكون المحتوى عاماً والجودة التي توفرها المنصة وتوافق الملف النهائي. كما أن الأمان مهم بسبب الصفحات المضللة وأزرار التنزيل الوهمية وطلبات تثبيت برامج غير ضرورية.", "هذه الطريقة للمحتوى العام الذي أنشأته أو لديك إذن بحفظه. وهي لا تتجاوز حساباً خاصاً أو اشتراكاً أو قيد وصول أو حماية تقنية. ستتعلم نسخ الرابط الصحيح واختيار صيغة منطقية وفحص النتيجة وتشخيص فشل التحويل."],
      sections: [
        { id: "permission", title: "ابدأ بالإذن والوصول العام", paragraphs: ["المحتوى الظاهر للعامة ليس بالضرورة خالياً من الحقوق. تأكد أنك صاحبه أو لديك إذن من المنشئ أو ترخيص يسمح بالاستخدام أو أن غرضك قانوني في بلدك. قد تنظم شروط المنصة أيضاً النسخ والاستخدام دون اتصال.", "الأداة المسؤولة لا تطلب بيانات حسابك ولا تعد بفتح الحسابات الخاصة. يجب أن تبقى المنشورات المخصصة للأصدقاء والمجموعات المغلقة والقصص المنتهية والفيديوهات المدفوعة غير متاحة، حماية لخصوصية الآخرين وحسابك."] },
        { id: "correct-link", title: "انسخ الرابط الصحيح من المنصة", paragraphs: ["استخدم زر المشاركة في المنشور الأصلي بدلاً من صفحة بحث أو مشغل مدمج. افتح فيديو YouTube أو Short العام، والمنشور نفسه في TikTok وInstagram وThreads. في Facebook تحقق من ظهوره في نافذة خاصة بدون تسجيل الدخول.", "تُرسل صور GIF في X غالباً كفيديو MP4 صغير. وفي Rumble انتظر انتهاء البث المباشر واستخدم النسخة المنشورة. الرابط النهائي أسهل في التشخيص من الرابط المختصر، وإذا كانت الصفحة تتطلب تسجيل الدخول فلا ينبغي تجاوز ذلك."], bullets: ["افتح المنشور الأصلي", "اختر مشاركة ثم نسخ الرابط", "اختبر الرابط بدون تسجيل الدخول", "تجنب الصفحات الخاصة وصفحات البحث"] },
        { id: "format-quality", title: "اختر الصيغة والجودة بدون تضخيم الملف", paragraphs: ["احتفظ بـ MP4 عندما تحتاج الصورة. استخدم MP3 أو M4A للاستماع، وWAV لبعض أعمال التحرير، وFLAC لتجنب فقدان إضافي مع مصدر مناسب، أو Opus عندما تهم الكفاءة. الاستخدام النهائي أهم من أكبر رقم في القائمة.", "تكفي 720p غالباً للهاتف، بينما تناسب 1080p الشاشة الأكبر إذا وفرها المصدر. قد تكفي 128 أو 192 kbps للكلام، ويمكن اختيار 256 أو 320 kbps للموسيقى. لا يعيد التحويل تفاصيل غير موجودة."] },
        { id: "security", title: "كيف تتعرف على تنزيل آمن؟", paragraphs: ["لا ينبغي أن يطلب المحول تثبيت إضافة مجهولة أو مشغل خاص للحصول على ملف عادي. افحص اسم النطاق واتصال HTTPS واسم الملف، وارفض الإشعارات غير الضرورية، ولا تدخل كلمة مرور منصة اجتماعية في محول خارجي.", "يجب تمييز الإعلان بوضوح. يظهر زر النتيجة بعد انتهاء التحويل ويشير إلى الملف، أما إعلان جائزة أو تحذير نظام أو تحديث عاجل فليس التنزيل. على الهاتف افحص مجلد التنزيلات وتعامل بحذر مع أي امتداد غير متوقع."] },
        { id: "troubleshooting", title: "أسباب فشل التحويل وما الذي تفحصه", paragraphs: ["قد يكون الرابط خاصاً أو محذوفاً أو مقيداً جغرافياً أو بثاً مباشراً. وقد تغير المنصة تقنياتها أو يزدحم الخادم أو تتعطل route شبكة مؤقتاً. جرّب الرابط الأصلي وتأكد من تشغيله بدون حساب وانتظر عند وجود تقييد مؤقت.", "إذا طلب YouTube تأكيد أنك لست روبوتاً فقد تؤدي المحاولات الكثيرة إلى زيادة الحظر. يمكن للخدمة تجربة مسار شبكة آخر لكنها لا تضمن كل فيديو. إذا كنت تملك الملف، فرفعه مباشرة هو الطريقة الأكثر ثباتاً لتغيير صيغته."], bullets: ["اختبر الرابط في نافذة خاصة", "احذف معاملات التتبع غير الضرورية", "جرّب دقة أقل عند غياب HD", "ارفع ملفك عندما تمنع المنصة الرابط"] },
        { id: "after-download", title: "بعد التنزيل: افحص الملف ونظمه", paragraphs: ["شغّل بداية الملف ووسطه ونهايته وتحقق من المدة والصوت والصورة والتزامن. قد يكون ملف MP4 الذي لا يفتح ناقصاً أو يستخدم ترميزاً غير مدعوم، ويقلل فحص FFprobe من هذا الخطر.", "أعد تسمية الملف بعنوان وتاريخ واسم المنشئ عند الحاجة، واحفظ معلومات الترخيص أو الإذن معه. احذف النسخ المؤقتة ولا تعِد نشر المحتوى كأنه ملكك. التنظيم الجيد يحفظ السياق ويسهل العثور عليه لاحقاً."] },
      ],
      faqs: [{ question: "هل يمكن تنزيل فيديو خاص؟", answer: "لا. لا ينبغي للمحول العام تجاوز تسجيل الدخول أو الحساب الخاص أو الاشتراك أو قيد الوصول." }, { question: "ما الصيغة المناسبة لـ iPhone وAndroid؟", answer: "يوفر MP4 بترميز H.264 وAAC توافقاً واسعاً، وللصوت فقط يناسب MP3 وM4A." }, { question: "لماذا لا يبدأ التنزيل؟", answer: "قد يكون الرابط غير متاح أو التحويل جارياً أو المتصفح حظر نافذة. استخدم زر النتيجة بعد اكتمال العملية فقط." }, { question: "هل يطلب المحول كلمة المرور؟", answer: "لا. لا تعط بيانات حسابك لأي محول خارجي." }],
      ctaTitle: "هل أنت مستعد لتحويل محتوى عام مصرح به؟", ctaText: "استخدم رابط المنشور الأصلي واختر جودة واقعية وافحص النتيجة قبل الاحتفاظ بها.", ctaLabel: "جرّب toTube",
    },
  },
  es: {
    "formats-guide": {
      id: "formats-guide", slug: "mp4-mp3-que-formato-elegir", title: "MP4, MP3, M4A, WAV, FLAC u OPUS: ¿qué formato elegir?", description: "Compara MP4, MP3, M4A, WAV, FLAC y OPUS para elegir formato, resolución y bitrate según tu dispositivo.", eyebrow: "Guía de formatos", readTime: "11", published: "2026-08-24", updated: "2026-08-24", keywords: ["MP4 o MP3", "mejor formato de vídeo", "M4A o MP3", "WAV o FLAC", "calidad 1080p", "MP3 320 kbps"],
      intro: ["Elegir un formato no consiste solo en seleccionar una extensión. Debes decidir si necesitas la imagen, saber qué dispositivos reproducirán el archivo, valorar el espacio disponible y respetar la calidad de la fuente. Un flujo público de 720p no gana detalle real al exportarlo con un límite de 1080p, y un audio comprimido no recupera información dentro de un archivo de 320 kbps.", "Esta guía separa contenedores, códecs, resolución y bitrate. Explica cuándo MP4 es la opción práctica para vídeo y qué diferencias hay entre MP3, M4A, AAC, WAV, FLAC y Opus. El objetivo es obtener un archivo adecuado, compatible y tan fiel como permita la fuente."],
      sections: [
        { id: "container-codec", title: "Contenedor, códec y extensión no son lo mismo", paragraphs: ["La extensión suele indicar el contenedor o formato. MP4 puede reunir vídeo, audio, subtítulos y metadatos. Dentro puede usar H.264 para imagen y AAC para sonido; por eso dos archivos .mp4 pueden comportarse de forma distinta.", "El códec describe cómo se comprimen imagen o sonido. H.264 y AAC tienen amplio soporte, mientras MP3, FLAC y Opus sirven a objetivos distintos. Cambiar el nombre de la extensión no convierte nada: una conversión real crea el flujo esperado y comprueba el resultado."] },
        { id: "mp4-video", title: "Elige MP4 cuando necesites conservar la imagen", paragraphs: ["MP4 con H.264 y AAC suele funcionar en iPhone, Android, Windows, macOS, televisores y programas de presentación. Es una buena opción para tutoriales, demostraciones y archivos personales autorizados.", "Ajusta la resolución a la pantalla y la fuente. 360p reduce el archivo, 720p equilibra calidad y tamaño en móvil y 1080p conserva más detalle si realmente existe. Si la plataforma solo ofrece 720p, ampliar a 1080p crea píxeles interpolados, no detalle real."], bullets: ["360p para archivos pequeños", "720p para móvil y tableta", "1080p para pantallas grandes si la fuente lo ofrece"] },
        { id: "audio-formats", title: "Diferencias útiles entre formatos de audio", paragraphs: ["MP3 ofrece máxima compatibilidad con coches y reproductores antiguos. M4A suele contener AAC y es eficiente en dispositivos modernos. Opus funciona muy bien para voz y streaming actual, aunque algunos equipos antiguos no lo aceptan.", "WAV suele ser audio sin comprimir y genera archivos grandes para edición. FLAC comprime sin perder los datos recibidos. Convertir una fuente ya comprimida a WAV o FLAC no recupera la información perdida; solo evita otra etapa con pérdida."], bullets: ["MP3: compatibilidad máxima", "M4A/AAC: eficiencia moderna", "WAV: edición y archivos grandes", "FLAC: almacenamiento sin pérdida adicional", "Opus: gran eficiencia, conviene comprobar compatibilidad"] },
        { id: "bitrate", title: "Entender el bitrate sin caer en la trampa de 320 kbps", paragraphs: ["El bitrate es la cantidad aproximada de datos usada cada segundo. 128 o 192 kbps puede bastar para voz; 256 o 320 kbps reduce pérdidas añadidas en música. La elección depende de la fuente, los auriculares y el espacio.", "Exportar MP3 a 320 kbps no demuestra que la fuente tuviera esa calidad. Si ya estaba muy comprimida, el bitrate superior aumenta sobre todo el tamaño. Un conversor transparente indica el objetivo sin prometer reconstruir detalles ausentes."] },
        { id: "device-choice", title: "Qué elegir según el dispositivo y el uso", paragraphs: ["Para compartir vídeo entre dispositivos, MP4 H.264/AAC es la opción segura. Para coche, USB o reproductor antiguo, MP3. M4A es compacto en móviles modernos; WAV resulta útil en edición y FLAC en archivos que merecen conservación sin pérdida adicional.", "Antes de convertir pregunta: ¿necesito la imagen?, ¿qué dispositivo reproducirá el archivo?, ¿qué calidad ofrece la fuente? y ¿cuánto espacio puedo usar? Así evitas incompatibilidades y tamaños innecesarios."] },
        { id: "verification", title: "Cómo reconocer un archivo bien convertido", paragraphs: ["El archivo debe abrirse, incluir las pistas previstas, tener una duración coherente y usar códecs compatibles. H.264, AAC y yuv420p ofrecen amplia compatibilidad en MP4. Un archivo de audio no debe conservar pista de vídeo y su códec debe corresponder a la extensión.", "toTube prepara el medio con FFmpeg y examina el resultado con FFprobe. La verificación no mejora una mala fuente, pero evita presentar un archivo renombrado, incompleto o mal codificado como MP3 o MP4 válido."] },
      ],
      faqs: [{ question: "¿Elijo MP4 o MP3?", answer: "MP4 conserva la imagen. MP3 sirve si solo necesitas audio y buscas máxima compatibilidad." }, { question: "¿320 kbps siempre suena mejor?", answer: "No. Reduce pérdidas del nuevo proceso, pero la fuente limita el resultado." }, { question: "¿FLAC es mejor que WAV?", answer: "Ambos pueden conservar sin pérdida. FLAC comprime y suele ocupar menos; WAV es cómodo en algunos flujos de edición." }, { question: "¿Por qué 1080p puede terminar en 720p?", answer: "Porque se respeta la mejor resolución real de la fuente en lugar de inventar detalle." }],
      ctaTitle: "Elige formato con calidad transparente", ctaText: "Pega un enlace público, elige MP4 o audio y selecciona una resolución o bitrate realista.", ctaLabel: "Convertir contenido público",
    },
    "safe-download-guide": {
      id: "safe-download-guide", slug: "descargar-video-online-seguridad", title: "Cómo descargar vídeo online de forma segura y con buena calidad", description: "Guía para descargar vídeo público autorizado, elegir calidad, evitar botones falsos y resolver errores de conversión.", eyebrow: "Guía práctica", readTime: "12", published: "2026-08-24", updated: "2026-08-24", keywords: ["descargar vídeo online", "descargar vídeo sin programa", "descargador seguro", "descargar vídeo iPhone", "descargar vídeo Android"],
      intro: ["Descargar vídeo parece sencillo: copiar la dirección, elegir formato y guardar. En la práctica depende del tipo de enlace, de si el contenido es público, de la calidad que entrega la plataforma y de la compatibilidad final. También importa la seguridad frente a páginas confusas, botones falsos y solicitudes de instalación innecesarias.", "Este método es para contenido público que has creado o que puedes conservar con autorización. No evita cuentas privadas, suscripciones, restricciones ni protecciones técnicas. Aprenderás a copiar el enlace correcto, escoger un formato razonable, comprobar el archivo y diagnosticar fallos."],
      sections: [
        { id: "permission", title: "Empieza por el acceso público y el permiso", paragraphs: ["Que un contenido sea visible no significa que esté libre de derechos. Confirma que eres su autor, que el creador te autorizó, que existe una licencia o que el uso es legal. Las condiciones de cada plataforma también pueden regular la copia.", "Una herramienta responsable no pide credenciales ni promete acceder a cuentas privadas. Publicaciones para amigos, grupos cerrados, stories caducadas, vídeos de pago y contenido eliminado deben seguir inaccesibles."] },
        { id: "correct-link", title: "Copia el enlace correcto de cada plataforma", paragraphs: ["Usa Compartir en la publicación original, no una página de búsqueda. En YouTube sirve un vídeo o Short público; en TikTok, Instagram y Threads abre el post. En Facebook verifica que sea visible en una ventana privada sin iniciar sesión.", "X suele servir los GIF como pequeños MP4. En Rumble espera a que termine el directo. El enlace final es más fácil de diagnosticar que uno acortado. Si la página exige acceso, el conversor público no debe evitarlo."], bullets: ["Abrir la publicación original", "Usar Compartir y Copiar enlace", "Comprobar sin iniciar sesión", "Evitar perfiles privados y búsquedas"] },
        { id: "format-quality", title: "Elige formato y calidad sin inflar el archivo", paragraphs: ["Mantén MP4 si necesitas imagen. Elige MP3 o M4A para escuchar, WAV para ciertos trabajos de edición, FLAC para evitar otra pérdida u Opus para eficiencia. El uso final debe decidir, no el número más grande.", "720p suele bastar en móvil y 1080p sirve en pantallas mayores si la fuente existe. Para voz pueden bastar 128 o 192 kbps; en música puedes elegir 256 o 320. La conversión no recrea detalles ausentes."] },
        { id: "security", title: "Reconoce un flujo de descarga seguro", paragraphs: ["Un conversor no debería exigir extensiones desconocidas ni reproductores especiales. Comprueba el dominio, HTTPS y el nombre del archivo. Rechaza notificaciones innecesarias y nunca introduzcas la contraseña de una red social.", "La publicidad debe estar identificada. El botón legítimo aparece tras convertir y menciona el archivo. Un premio, aviso del sistema o actualización urgente no es el resultado. En móvil revisa Descargas o Archivos y desconfía de extensiones inesperadas."] },
        { id: "troubleshooting", title: "Por qué falla una conversión", paragraphs: ["El enlace puede ser privado, eliminado, regional o en directo. También puede haber cambios técnicos, saturación o una ruta de red no disponible. Prueba la URL original, confirma que funciona sin cuenta y espera si existe un límite temporal.", "Si YouTube pide confirmar que no eres un robot, repetir muchas veces puede agravar el bloqueo. Otra ruta puede ayudar, pero ningún servicio garantiza todos los vídeos. Si ya tienes el archivo, subirlo directamente es más fiable."], bullets: ["Probar en una ventana privada", "Quitar parámetros de seguimiento", "Elegir menor calidad si falta HD", "Subir tu archivo cuando el enlace esté bloqueado"] },
        { id: "after-download", title: "Después: comprueba y organiza el archivo", paragraphs: ["Reproduce el principio, centro y final. Comprueba duración, sonido, imagen y sincronización. Un MP4 que no abre puede estar incompleto o usar un códec incompatible; FFprobe reduce ese riesgo.", "Renombra con título, fecha y creador cuando corresponda. Guarda la licencia o autorización, elimina copias temporales y no publiques el contenido como propio. Una buena organización conserva su contexto."] },
      ],
      faqs: [{ question: "¿Puedo descargar un vídeo privado?", answer: "No. Un conversor público no debe evitar cuentas privadas, acceso, suscripciones ni restricciones." }, { question: "¿Qué formato funciona en iPhone y Android?", answer: "MP4 H.264/AAC es ampliamente compatible; MP3 y M4A funcionan bien para audio." }, { question: "¿Por qué no empieza la descarga?", answer: "El enlace puede ser inaccesible, la conversión puede seguir activa o el navegador bloqueó una ventana. Usa solo el control final." }, { question: "¿Debe pedir mi contraseña?", answer: "No. Nunca entregues credenciales a un conversor externo." }],
      ctaTitle: "¿Listo para convertir contenido público autorizado?", ctaText: "Usa el enlace original, elige calidad realista y comprueba el archivo final.", ctaLabel: "Probar toTube",
    },
  },
  pt: {
    "formats-guide": {
      id: "formats-guide", slug: "mp4-mp3-qual-formato-escolher", title: "MP4, MP3, M4A, WAV, FLAC ou OPUS: qual formato escolher?", description: "Compare MP4, MP3, M4A, WAV, FLAC e OPUS para escolher formato, resolução e bitrate para cada aparelho.", eyebrow: "Guia de formatos", readTime: "11", published: "2026-08-24", updated: "2026-08-24", keywords: ["MP4 ou MP3", "melhor formato de vídeo", "M4A ou MP3", "WAV ou FLAC", "qualidade 1080p", "MP3 320 kbps"],
      intro: ["Escolher um formato não é apenas selecionar a extensão. É preciso decidir se a imagem importa, saber quais aparelhos reproduzirão o arquivo, considerar o espaço e respeitar a qualidade da fonte. Um fluxo público em 720p não ganha detalhes reais ao ser exportado com limite de 1080p, e um áudio comprimido não recupera informação em um arquivo de 320 kbps.", "Este guia separa contêiner, codec, resolução e bitrate. Ele explica quando MP4 é a escolha prática para vídeo e como MP3, M4A, AAC, WAV, FLAC e Opus se diferenciam. O objetivo é obter um arquivo adequado, compatível e tão fiel quanto a fonte permite."],
      sections: [
        { id: "container-codec", title: "Contêiner, codec e extensão não são a mesma coisa", paragraphs: ["A extensão geralmente indica o contêiner. MP4 pode reunir vídeo, áudio, legendas e metadados. Dentro dele, H.264 pode codificar a imagem e AAC o som; por isso dois arquivos .mp4 podem ter compatibilidade diferente.", "O codec define como imagem ou som são comprimidos. H.264 e AAC têm amplo suporte, enquanto MP3, FLAC e Opus atendem necessidades diferentes. Apenas renomear a extensão não converte o arquivo: é preciso criar o fluxo correto e verificar o resultado."] },
        { id: "mp4-video", title: "Escolha MP4 quando precisar da imagem", paragraphs: ["MP4 com H.264 e AAC costuma funcionar em iPhone, Android, Windows, macOS, TVs e apresentações. É uma opção útil para tutoriais, demonstrações e arquivos pessoais autorizados.", "Ajuste a resolução à tela e à fonte. 360p reduz o tamanho, 720p equilibra qualidade no celular e 1080p conserva mais detalhe se ele existir. Se a plataforma só fornece 720p, ampliar para 1080p interpola pixels, não cria detalhes."], bullets: ["360p para arquivos menores", "720p para celular e tablet", "1080p para telas maiores quando disponível"] },
        { id: "audio-formats", title: "Diferenças úteis entre os formatos de áudio", paragraphs: ["MP3 oferece compatibilidade máxima com carros e aparelhos antigos. M4A costuma conter AAC e é eficiente em dispositivos modernos. Opus é eficiente para voz e streaming, mas pode ter menos suporte em equipamentos antigos.", "WAV costuma ser não comprimido e gera arquivos grandes para edição. FLAC comprime sem perder os dados recebidos. Converter uma fonte já comprimida para WAV ou FLAC não recupera informação; apenas evita nova perda em etapas futuras."], bullets: ["MP3: compatibilidade máxima", "M4A/AAC: eficiência moderna", "WAV: edição e arquivos grandes", "FLAC: armazenamento sem perda adicional", "Opus: eficiência com compatibilidade a verificar"] },
        { id: "bitrate", title: "Entenda o bitrate sem cair na armadilha dos 320 kbps", paragraphs: ["O bitrate é a quantidade aproximada de dados por segundo. 128 ou 192 kbps pode bastar para voz; 256 ou 320 kbps reduz perdas adicionais na música. A escolha depende da fonte, dos fones e do espaço.", "Exportar MP3 em 320 kbps não prova que a fonte tinha essa qualidade. Se ela já estava comprimida, o bitrate maior aumenta principalmente o tamanho. Um conversor transparente informa o alvo sem prometer reconstruir detalhes ausentes."] },
        { id: "device-choice", title: "A melhor escolha por aparelho e uso", paragraphs: ["Para vídeo entre aparelhos, MP4 H.264/AAC é uma escolha segura. Para carro, USB ou player antigo, use MP3. M4A é compacto em celulares; WAV ajuda em edição e FLAC em arquivos que justificam conservação sem nova perda.", "Antes de converter pergunte: preciso da imagem? qual aparelho tocará o arquivo? qual qualidade a fonte oferece? quanto espaço posso usar? Isso evita incompatibilidades e tamanhos desnecessários."] },
        { id: "verification", title: "Como reconhecer um arquivo bem convertido", paragraphs: ["O arquivo deve abrir, conter as faixas esperadas, ter duração coerente e codecs compatíveis. H.264, AAC e yuv420p oferecem amplo suporte em MP4. No áudio, não deve restar faixa de vídeo e o codec precisa corresponder à extensão.", "O toTube prepara o arquivo com FFmpeg e examina com FFprobe. A verificação não melhora uma fonte ruim, mas evita apresentar um arquivo renomeado, incompleto ou mal codificado como MP3 ou MP4 válido."] },
      ],
      faqs: [{ question: "Escolho MP4 ou MP3?", answer: "MP4 mantém a imagem. MP3 serve quando você precisa apenas do áudio e quer compatibilidade máxima." }, { question: "320 kbps é sempre melhor?", answer: "Não. Pode reduzir perdas do novo encode, mas a fonte limita o resultado." }, { question: "FLAC é melhor que WAV?", answer: "Ambos podem preservar sem perda. FLAC comprime e ocupa menos; WAV é útil em alguns fluxos de edição." }, { question: "Por que 1080p pode virar 720p?", answer: "Porque o conversor respeita a melhor resolução real da fonte, sem inventar detalhes." }],
      ctaTitle: "Escolha o formato com qualidade transparente", ctaText: "Cole um link público, escolha MP4 ou áudio e selecione uma resolução ou bitrate realista.", ctaLabel: "Converter mídia pública",
    },
    "safe-download-guide": {
      id: "safe-download-guide", slug: "baixar-video-online-com-seguranca", title: "Como baixar vídeo online com segurança e boa qualidade", description: "Guia para baixar vídeo público autorizado, escolher qualidade, evitar botões falsos e resolver erros de conversão.", eyebrow: "Guia prático", readTime: "12", published: "2026-08-24", updated: "2026-08-24", keywords: ["baixar vídeo online", "baixar vídeo sem programa", "downloader seguro", "baixar vídeo iPhone", "baixar vídeo Android"],
      intro: ["Baixar vídeo parece simples: copiar o endereço, escolher o formato e salvar. Na prática, depende do tipo de link, do acesso público, da qualidade fornecida e da compatibilidade final. A segurança também importa por causa de páginas enganosas, botões falsos e pedidos de instalação desnecessários.", "Este processo serve para conteúdo público que você criou ou tem autorização para guardar. Ele não contorna contas privadas, assinaturas, restrições ou proteções técnicas. Você aprenderá a copiar o link correto, escolher um formato razoável, verificar o arquivo e diagnosticar falhas."],
      sections: [
        { id: "permission", title: "Comece pelo acesso público e pela permissão", paragraphs: ["Conteúdo visível não é automaticamente livre de direitos. Confirme que você é o autor, recebeu permissão, possui uma licença ou que o uso é legal. Os termos da plataforma também podem limitar cópia e uso offline.", "Uma ferramenta responsável não pede credenciais nem promete abrir contas privadas. Posts para amigos, grupos fechados, stories expirados, vídeos pagos e conteúdo removido devem continuar inacessíveis."] },
        { id: "correct-link", title: "Copie o link correto da plataforma", paragraphs: ["Use Compartilhar no post original, não uma página de busca. No YouTube use vídeo ou Short público; em TikTok, Instagram e Threads abra o post. No Facebook verifique se ele aparece em janela anônima sem login.", "O X costuma entregar GIFs como pequenos MP4. No Rumble espere a live terminar. A URL final é mais fácil de diagnosticar que um link curto. Se a página exige login, o conversor público não deve contornar isso."], bullets: ["Abrir o post original", "Usar Compartilhar e Copiar link", "Testar sem login", "Evitar perfis privados e buscas"] },
        { id: "format-quality", title: "Escolha formato e qualidade sem inflar o arquivo", paragraphs: ["Mantenha MP4 se precisa da imagem. Use MP3 ou M4A para ouvir, WAV em alguns trabalhos de edição, FLAC para evitar nova perda ou Opus para eficiência. O uso final deve definir o formato.", "720p costuma bastar no celular e 1080p serve em telas maiores se a fonte oferece. 128 ou 192 kbps pode ser suficiente para voz; 256 ou 320 para música. A conversão não recria detalhes ausentes."] },
        { id: "security", title: "Reconheça um download seguro", paragraphs: ["Um conversor não deve exigir extensão desconhecida ou player especial. Confira o domínio, HTTPS e o nome do arquivo. Recuse notificações desnecessárias e nunca informe senha de rede social.", "A publicidade precisa estar identificada. O botão legítimo aparece após a conversão e menciona o arquivo. Prêmios, alertas do sistema e atualizações urgentes não são o resultado. No celular, revise a pasta Downloads e extensões inesperadas."] },
        { id: "troubleshooting", title: "Por que a conversão falha", paragraphs: ["O link pode ser privado, removido, regional ou ao vivo. Pode haver mudança técnica, servidor ocupado ou rota de rede indisponível. Teste a URL original sem login e aguarde limitações temporárias.", "Se o YouTube pedir confirmação contra robôs, repetir muitas vezes pode ampliar o bloqueio. Outra rota pode ajudar, mas nenhum serviço garante todo vídeo. Se você já possui o arquivo, o upload direto é mais confiável."], bullets: ["Testar em janela anônima", "Remover parâmetros de rastreamento", "Tentar qualidade menor", "Enviar seu arquivo quando o link estiver bloqueado"] },
        { id: "after-download", title: "Depois: verifique e organize o arquivo", paragraphs: ["Reproduza início, meio e fim. Confira duração, som, imagem e sincronização. Um MP4 que não abre pode estar incompleto ou usar codec incompatível; FFprobe reduz esse risco.", "Renomeie com título, data e criador, guarde a licença ou permissão, remova cópias temporárias e não publique como se fosse seu. Boa organização preserva o contexto."] },
      ],
      faqs: [{ question: "Posso baixar vídeo privado?", answer: "Não. Um conversor público não deve contornar login, conta privada, assinatura ou restrição." }, { question: "Qual formato funciona no iPhone e Android?", answer: "MP4 H.264/AAC tem amplo suporte; MP3 e M4A são práticos para áudio." }, { question: "Por que o download não começa?", answer: "O link pode estar inacessível, a conversão pode estar ativa ou o navegador bloqueou uma janela. Use o controle final." }, { question: "Devo informar minha senha?", answer: "Não. Nunca forneça credenciais a um conversor externo." }],
      ctaTitle: "Pronto para converter conteúdo público autorizado?", ctaText: "Use o link original, escolha qualidade realista e verifique o resultado.", ctaLabel: "Testar o toTube",
    },
  },
  de: {
    "formats-guide": {
      id: "formats-guide", slug: "mp4-mp3-welches-format-waehlen", title: "MP4, MP3, M4A, WAV, FLAC oder OPUS: Welches Format passt?", description: "MP4, MP3, M4A, WAV, FLAC und OPUS vergleichen und Format, Auflösung sowie Bitrate passend zum Gerät wählen.", eyebrow: "Format-Ratgeber", readTime: "11", published: "2026-08-24", updated: "2026-08-24", keywords: ["MP4 oder MP3", "bestes Videoformat", "M4A oder MP3", "WAV oder FLAC", "1080p Qualität", "MP3 320 kbps"],
      intro: ["Bei der Formatwahl geht es um mehr als die Dateiendung. Entscheidend sind Bildbedarf, Wiedergabegeräte, Speicherplatz und die tatsächliche Qualität der Quelle. Ein öffentlicher 720p-Stream erhält durch eine 1080p-Ausgabe keine echten Details, und stark komprimiertes Audio gewinnt in einer 320-kbps-Datei keine verlorenen Informationen zurück.", "Dieser Ratgeber trennt Container, Codec, Auflösung und Bitrate. Er erklärt MP4 für Video und die Unterschiede zwischen MP3, M4A, AAC, WAV, FLAC und Opus. Ziel ist eine passende, kompatible Datei, die der verfügbaren Quelle möglichst treu bleibt."],
      sections: [
        { id: "container-codec", title: "Container, Codec und Endung sind nicht dasselbe", paragraphs: ["Die Endung bezeichnet meist Container oder Dateiformat. MP4 kann Video, Audio, Untertitel und Metadaten bündeln. Darin können H.264 für das Bild und AAC für den Ton stecken. Deshalb können zwei .mp4-Dateien unterschiedlich kompatibel sein.", "Ein Codec beschreibt die Kompression. H.264 und AAC werden breit unterstützt; MP3, FLAC und Opus verfolgen unterschiedliche Ziele. Das Umbenennen einer Endung konvertiert nichts. Eine echte Konvertierung erzeugt den erwarteten Stream und prüft das Ergebnis."] },
        { id: "mp4-video", title: "MP4 wählen, wenn das Bild erhalten bleiben soll", paragraphs: ["MP4 mit H.264 und AAC funktioniert meist auf iPhone, Android, Windows, macOS, Fernsehern und in Präsentationen. Es eignet sich für Anleitungen, Demonstrationen und erlaubte persönliche Archive.", "Passe die Auflösung an Quelle und Bildschirm an. 360p spart Platz, 720p ist ein guter mobiler Kompromiss und 1080p bewahrt mehr Details, wenn die Quelle sie liefert. Ist nur 720p verfügbar, erzeugt Hochskalieren keine echten Details."], bullets: ["360p für kleine Dateien", "720p für Handy und Tablet", "1080p für größere Bildschirme bei echter Verfügbarkeit"] },
        { id: "audio-formats", title: "Praktische Unterschiede der Audioformate", paragraphs: ["MP3 bietet maximale Kompatibilität mit Autos und älteren Playern. M4A enthält häufig AAC und ist auf modernen Geräten effizient. Opus eignet sich sehr gut für Sprache und modernes Streaming, wird aber von älterer Hardware nicht immer unterstützt.", "WAV ist oft unkomprimiert und groß, was bei Bearbeitung nützlich sein kann. FLAC komprimiert die zugeführten Daten verlustfrei. Eine bereits verlustbehaftete Quelle wird durch WAV oder FLAC nicht repariert; nur eine weitere Verluststufe wird vermieden."], bullets: ["MP3: höchste Kompatibilität", "M4A/AAC: moderne Effizienz", "WAV: Bearbeitung und große Dateien", "FLAC: verlustfreie Speicherung", "Opus: hohe Effizienz, Kompatibilität prüfen"] },
        { id: "bitrate", title: "Bitrate verstehen, ohne in die 320-kbps-Falle zu geraten", paragraphs: ["Die Bitrate beschreibt ungefähr die Datenmenge pro Sekunde. Für Sprache reichen oft 128 oder 192 kbps. Bei Musik können 256 oder 320 kbps zusätzliche Verluste verringern. Quelle, Kopfhörer und Speicher entscheiden mit.", "Ein Export mit 320 kbps beweist keine entsprechende Quellqualität. War das Audio stark komprimiert, wächst vor allem die Datei. Ein transparenter Konverter nennt das Ziel, ohne fehlende Details zu versprechen."] },
        { id: "device-choice", title: "Die richtige Wahl für Gerät und Einsatz", paragraphs: ["Für Video auf mehreren Geräten ist MP4 H.264/AAC die sichere Wahl. Für Auto, USB-Stick oder alten Player eignet sich MP3. M4A ist kompakt auf modernen Handys; WAV hilft in manchen Bearbeitungsabläufen und FLAC bei sinnvoller verlustfreier Archivierung.", "Frage vorab: Brauche ich das Bild? Welches Gerät spielt die Datei? Welche Qualität bietet die Quelle? Wie viel Speicher steht zur Verfügung? Das verhindert inkompatible und unnötig große Dateien."] },
        { id: "verification", title: "Eine korrekt konvertierte Datei erkennen", paragraphs: ["Die Datei sollte sich öffnen, erwartete Spuren enthalten, eine plausible Dauer zeigen und unterstützte Codecs nutzen. H.264, AAC und yuv420p bieten breite MP4-Kompatibilität. Bei Audio darf keine Videospur übrig bleiben und Codec sowie Endung müssen zusammenpassen.", "toTube bereitet Medien mit FFmpeg vor und prüft sie mit FFprobe. Das verbessert keine schlechte Quelle, verhindert aber, dass umbenannte, unvollständige oder falsch codierte Dateien als funktionierende MP3 oder MP4 angeboten werden."] },
      ],
      faqs: [{ question: "MP4 oder MP3 wählen?", answer: "MP4 behält das Bild. MP3 ist richtig, wenn nur Audio und maximale Kompatibilität benötigt werden." }, { question: "Ist 320 kbps immer besser?", answer: "Nein. Die neue Codierung kann weniger verlieren, aber die Quelle begrenzt das Ergebnis." }, { question: "Ist FLAC besser als WAV?", answer: "Beide können verlustfrei sein. FLAC spart meist Platz, WAV ist in manchen Bearbeitungsabläufen praktisch." }, { question: "Warum entstehen bei 1080p manchmal nur 720p?", answer: "Weil der Konverter die beste echte Quellauflösung respektiert, statt Details zu erfinden." }],
      ctaTitle: "Format mit transparenter Qualität wählen", ctaText: "Öffentlichen Link einfügen, MP4 oder Audio wählen und eine realistische Auflösung oder Bitrate festlegen.", ctaLabel: "Öffentliche Medien konvertieren",
    },
    "safe-download-guide": {
      id: "safe-download-guide", slug: "video-online-sicher-herunterladen", title: "Videos online sicher herunterladen: Qualität, Formate und Fehlerhilfe", description: "Ratgeber für erlaubte öffentliche Videos, passende Qualität, Schutz vor falschen Buttons und häufige Konvertierungsfehler.", eyebrow: "Praxis-Ratgeber", readTime: "12", published: "2026-08-24", updated: "2026-08-24", keywords: ["Video online herunterladen", "Video ohne Software herunterladen", "sicherer Video Downloader", "Video auf iPhone laden", "Video Android herunterladen"],
      intro: ["Ein Online-Download klingt einfach: Adresse kopieren, Format wählen und speichern. In der Praxis hängen Erfolg und Qualität vom Link, öffentlichen Zugriff, verfügbaren Stream und der Kompatibilität ab. Sicherheit ist ebenfalls wichtig, weil irreführende Seiten, falsche Buttons und unnötige Installationen verbreitet sind.", "Diese Methode gilt für öffentliche Medien, die du erstellt hast oder speichern darfst. Sie umgeht keine privaten Konten, Abos, Zugriffsbeschränkungen oder Schutzmaßnahmen. Du lernst, den richtigen Link zu kopieren, sinnvoll zu wählen, das Ergebnis zu prüfen und Fehler zu diagnostizieren."],
      sections: [
        { id: "permission", title: "Mit öffentlichem Zugriff und Erlaubnis beginnen", paragraphs: ["Öffentlich sichtbar bedeutet nicht automatisch frei von Rechten. Prüfe Urheberschaft, Erlaubnis, Lizenz oder die Rechtmäßigkeit deines Zwecks. Auch Plattformbedingungen können Kopien und Offline-Nutzung regeln.", "Ein verantwortungsvolles Tool fragt nicht nach Zugangsdaten und verspricht keinen Zugriff auf private Konten. Beiträge nur für Freunde, geschlossene Gruppen, abgelaufene Stories, bezahlte und gelöschte Videos müssen unzugänglich bleiben."] },
        { id: "correct-link", title: "Den richtigen Link von der Plattform kopieren", paragraphs: ["Nutze Teilen am Originalbeitrag statt einer Suchseite. Bei YouTube eignen sich öffentliche Videos und Shorts; bei TikTok, Instagram und Threads öffnest du den Beitrag. Facebook-Inhalte sollten ohne Anmeldung im privaten Fenster sichtbar sein.", "X liefert GIFs oft als kleine MP4-Videos. Bei Rumble sollte der Livestream beendet sein. Die endgültige Beitrags-URL ist leichter zu prüfen als ein Kurzlink. Verlangt die Seite einen Login, darf ein öffentlicher Konverter das nicht umgehen."], bullets: ["Originalbeitrag öffnen", "Teilen und Link kopieren", "Ohne Anmeldung testen", "Private Profile und Suchseiten vermeiden"] },
        { id: "format-quality", title: "Format und Qualität ohne unnötige Dateigröße wählen", paragraphs: ["MP4 behält das Bild. MP3 oder M4A eignen sich zum Hören, WAV für bestimmte Bearbeitung, FLAC gegen weitere Verluste und Opus für Effizienz. Der Zweck entscheidet, nicht die größte Zahl.", "720p reicht oft am Handy, 1080p passt zu größeren Bildschirmen, wenn die Quelle es liefert. 128 oder 192 kbps kann für Sprache genügen; 256 oder 320 für Musik. Konvertierung rekonstruiert keine fehlenden Details."] },
        { id: "security", title: "Einen sicheren Download erkennen", paragraphs: ["Ein Konverter sollte keine unbekannte Erweiterung oder Spezialsoftware verlangen. Prüfe Domain, HTTPS und Dateiname. Lehne unnötige Benachrichtigungen ab und gib niemals dein Plattform-Passwort ein.", "Werbung muss erkennbar sein. Der echte Download erscheint nach der Konvertierung und nennt die Datei. Gewinnversprechen, Systemwarnungen und dringende Updates sind nicht das Ergebnis. Prüfe auf Mobilgeräten den Download-Ordner und unerwartete Endungen."] },
        { id: "troubleshooting", title: "Warum eine Konvertierung scheitert", paragraphs: ["Links können privat, gelöscht, regional begrenzt oder live sein. Technische Änderungen, Last oder eine ausgefallene Netzwerkroute sind ebenfalls möglich. Teste die Original-URL ohne Anmeldung und warte bei temporären Limits.", "Fordert YouTube eine Bot-Bestätigung, können viele Wiederholungen die Sperre verschärfen. Eine andere Route kann helfen, garantiert aber nicht jedes Video. Besitzt du die Datei bereits, ist direkter Upload zuverlässiger."], bullets: ["Im privaten Fenster testen", "Tracking-Parameter entfernen", "Niedrigere Qualität versuchen", "Eigene Datei bei Link-Sperre hochladen"] },
        { id: "after-download", title: "Danach: Datei prüfen und organisieren", paragraphs: ["Spiele Anfang, Mitte und Ende ab. Prüfe Dauer, Ton, Bild und Synchronität. Eine nicht abspielbare MP4 kann unvollständig sein oder einen inkompatiblen Codec nutzen; FFprobe reduziert dieses Risiko.", "Benenne die Datei mit Titel, Datum und Urheber, bewahre Lizenz oder Erlaubnis auf, lösche temporäre Kopien und veröffentliche sie nicht als eigenes Werk. Gute Organisation erhält den Kontext."] },
      ],
      faqs: [{ question: "Kann ich private Videos herunterladen?", answer: "Nein. Ein öffentlicher Konverter darf Login, Privatkonto, Abo oder Zugriffsbeschränkung nicht umgehen." }, { question: "Welches Format läuft auf iPhone und Android?", answer: "MP4 mit H.264/AAC ist breit kompatibel; für Audio eignen sich MP3 und M4A." }, { question: "Warum startet der Download nicht?", answer: "Der Link kann unzugänglich sein, die Konvertierung läuft noch oder der Browser blockiert ein Fenster. Nutze nur die fertige Ergebnis-Schaltfläche." }, { question: "Soll ein Konverter mein Passwort verlangen?", answer: "Nein. Gib einem externen Konverter niemals Zugangsdaten." }],
      ctaTitle: "Bereit für erlaubte öffentliche Medien?", ctaText: "Original-Link verwenden, realistische Qualität wählen und die fertige Datei prüfen.", ctaLabel: "toTube testen",
    },
  },
};

export function blogIndexPath(locale: Locale) {
  return `/${locale}/blog`;
}

export function blogPostPath(locale: Locale, id: BlogPostId) {
  return `${blogIndexPath(locale)}/${blogPosts[locale][id].slug}`;
}

export function blogPostForSlug(locale: Locale, slug: string): BlogPost | null {
  return blogPostIds.map((id) => blogPosts[locale][id]).find((post) => post.slug === slug) || null;
}

export function blogPostLanguageAlternates(id: BlogPostId) {
  return Object.fromEntries([
    ...locales.map((locale) => [locale, `https://totube.online${blogPostPath(locale, id)}`]),
    ["x-default", `https://totube.online${blogPostPath("en", id)}`],
  ]);
}

export function blogIndexLanguageAlternates() {
  return Object.fromEntries([
    ...locales.map((locale) => [locale, `https://totube.online${blogIndexPath(locale)}`]),
    ["x-default", `https://totube.online${blogIndexPath("en")}`],
  ]);
}
