import { ArrowRight, Check, FileAudio, FileVideo, Gauge, Play, ShieldCheck } from "lucide-react";
import Link from "next/link";
import AdBanner from "./ad-banner";
import { AD_KEYS } from "./ad-config";
import { homeCopy, Locale, platformPath, qualityPagePath, QualityPageId } from "./i18n";
import { ToolFooter, ToolNavigation } from "./tool-navigation";

type QualityContent = {
  home: string;
  convert: string;
  free: string;
  verified: string;
  selectable: string;
  guide: string;
  questions: string;
  related: string;
  footer: string;
  title: string;
  accent: string;
  description: string;
  sections: { title: string; text: string }[];
  faqs: { question: string; answer: string }[];
};

const qualityContent: Record<Locale, Record<QualityPageId, QualityContent>> = {
  fr: {
    "youtube-mp3-320": { home: "Accueil", convert: "Convertir en MP3", free: "Gratuit", verified: "Codec vérifié", selectable: "128 à 320 kbps", guide: "Guide qualité audio", questions: "Questions fréquentes", related: "Formats associés", footer: "Conversion transparente avec contrôle du fichier final.", title: "YouTube MP3 320 kbps", accent: "avec un vrai encodage audio.", description: "Convertissez une vidéo YouTube publique en MP3 et choisissez 128, 192, 256 ou 320 kbps. Le fichier final est contrôlé avant téléchargement.", sections: [{ title: "Choisir 128, 192, 256 ou 320 kbps", text: "128 kbps convient aux voix et petits fichiers. 192 ou 256 kbps offrent un bon équilibre, tandis que 320 kbps privilégie la qualité pour la musique lorsque la source le permet." }, { title: "Pourquoi 320 kbps n’améliore pas une mauvaise source", text: "Un débit élevé limite les pertes pendant le nouvel encodage mais ne recrée pas les détails absents de la vidéo d’origine. toTube annonce donc le débit de sortie sans prétendre dépasser la source." }, { title: "Un véritable fichier MP3", text: "Le serveur extrait l’audio avec FFmpeg puis utilise FFprobe pour confirmer qu’une piste MP3 réelle existe et qu’aucune piste vidéo ne reste dans le fichier." }], faqs: [{ question: "Le MP3 est-il vraiment encodé à 320 kbps ?", answer: "Lorsque 320 kbps est sélectionné, FFmpeg reçoit ce débit cible. Le résultat dépend toujours de la qualité audio de la source." }, { question: "Quel débit choisir pour la voix ?", answer: "128 ou 192 kbps suffit généralement pour une conférence, un podcast ou une interview." }, { question: "Le fichier est-il compatible avec mon téléphone ?", answer: "Oui. MP3 est pris en charge par la grande majorité des téléphones, voitures, ordinateurs et lecteurs audio." }] },
    "youtube-mp4-1080": { home: "Accueil", convert: "Convertir en MP4", free: "Gratuit", verified: "H.264/AAC vérifié", selectable: "360p à 1080p", guide: "Guide qualité vidéo", questions: "Questions fréquentes", related: "Formats associés", footer: "Conversion transparente avec contrôle du fichier final.", title: "YouTube MP4 1080p", accent: "compatible avec vos appareils.", description: "Téléchargez une vidéo YouTube publique en MP4 et choisissez une résolution jusqu’à 1080p. Chaque sortie est vérifiée pour une lecture fiable.", sections: [{ title: "Choisir 360p, 480p, 720p ou 1080p", text: "360p réduit fortement la taille du fichier. 720p convient à la plupart des écrans mobiles et 1080p conserve davantage de détails lorsque cette qualité est réellement proposée par la source." }, { title: "Pourquoi nous disons « jusqu’à 1080p »", text: "toTube ne fabrique pas de résolution absente. Si la meilleure version publique disponible est en 720p, le résultat restera en 720p même si la limite choisie est 1080p." }, { title: "MP4 H.264 et AAC contrôlé", text: "Après téléchargement et fusion, le serveur vérifie la vidéo H.264, l’audio AAC et le profil de pixels yuv420p. Il réencode uniquement lorsque cela est nécessaire pour la compatibilité." }], faqs: [{ question: "Puis-je obtenir une vraie vidéo 1080p ?", answer: "Oui si la source publique propose réellement cette résolution. Sinon toTube utilise la meilleure qualité disponible sous la limite choisie." }, { question: "Pourquoi ne pas proposer 4K ?", answer: "La limite actuelle de 1080p protège la stabilité du service et évite de promettre une qualité que le serveur ne peut pas garantir partout." }, { question: "Le MP4 fonctionne-t-il avec QuickTime ?", answer: "Le profil H.264/AAC et yuv420p est choisi pour une large compatibilité, notamment avec QuickTime, iPhone, Android et téléviseurs." }] },
  },
  en: {
    "youtube-mp3-320": { home: "Home", convert: "Convert to MP3", free: "Free", verified: "Verified codec", selectable: "128 to 320 kbps", guide: "Audio quality guide", questions: "Frequently asked questions", related: "Related formats", footer: "Transparent conversion with final-file checks.", title: "YouTube to MP3 320 kbps", accent: "with real audio encoding.", description: "Convert a public YouTube video to MP3 and choose 128, 192, 256 or 320 kbps. The finished file is checked before download.", sections: [{ title: "Choose 128, 192, 256 or 320 kbps", text: "128 kbps is efficient for speech. 192 or 256 kbps balances size and sound, while 320 kbps prioritizes music quality when the source supports it." }, { title: "Why 320 kbps cannot repair a poor source", text: "A higher output bitrate reduces additional encoding loss but cannot restore detail missing from the original video. toTube states the output target without claiming to improve the source." }, { title: "A real MP3 file", text: "FFmpeg extracts and encodes the audio, then FFprobe confirms that the result contains a genuine MP3 audio stream and no remaining video track." }], faqs: [{ question: "Is the MP3 really encoded at 320 kbps?", answer: "When selected, FFmpeg receives a 320 kbps target. The audible result still depends on the source audio." }, { question: "Which bitrate is best for speech?", answer: "128 or 192 kbps is usually enough for lectures, podcasts and interviews." }, { question: "Will the file play on my phone?", answer: "Yes. MP3 works with nearly every phone, car system, computer and audio player." }] },
    "youtube-mp4-1080": { home: "Home", convert: "Convert to MP4", free: "Free", verified: "Verified H.264/AAC", selectable: "360p to 1080p", guide: "Video quality guide", questions: "Frequently asked questions", related: "Related formats", footer: "Transparent conversion with final-file checks.", title: "YouTube to MP4 1080p", accent: "built for compatible playback.", description: "Download a public YouTube video as MP4 and select a resolution up to 1080p. Every output is checked for reliable playback.", sections: [{ title: "Choose 360p, 480p, 720p or 1080p", text: "360p keeps files small, 720p suits most mobile screens, and 1080p preserves more detail when the source genuinely provides it." }, { title: "Why we say “up to 1080p”", text: "toTube does not invent missing pixels. If the best public version is 720p, the result remains 720p even when your selected ceiling is 1080p." }, { title: "Checked H.264 and AAC MP4", text: "After download and merging, the server verifies H.264 video, AAC audio and yuv420p pixels. It re-encodes only when needed for compatibility." }], faqs: [{ question: "Can I get a real 1080p video?", answer: "Yes, when the public source actually offers 1080p. Otherwise toTube selects the best quality below your chosen limit." }, { question: "Why is 4K not offered?", answer: "The current 1080p ceiling keeps the service stable and avoids promising a resolution we cannot reliably deliver for every source." }, { question: "Does the MP4 work in QuickTime?", answer: "The H.264/AAC and yuv420p profile is designed for broad compatibility with QuickTime, iPhone, Android and TVs." }] },
  },
  ar: {
    "youtube-mp3-320": { home: "الرئيسية", convert: "تحويل إلى MP3", free: "مجاني", verified: "ترميز متحقق", selectable: "128 إلى 320 kbps", guide: "دليل جودة الصوت", questions: "الأسئلة الشائعة", related: "صيغ مرتبطة", footer: "تحويل واضح مع فحص الملف النهائي.", title: "YouTube إلى MP3 320 kbps", accent: "بترميز صوتي حقيقي.", description: "حوّل فيديو YouTube عاماً إلى MP3 واختر 128 أو 192 أو 256 أو 320 kbps. يتم فحص الملف قبل التنزيل.", sections: [{ title: "اختر معدل الصوت", text: "يناسب 128 kbps الكلام والملفات الصغيرة، ويوازن 192 أو 256 بين الحجم والجودة، بينما يعطي 320 أولوية للموسيقى عندما تسمح جودة المصدر." }, { title: "لماذا لا يصلح 320 kbps مصدراً ضعيفاً", text: "يقلل المعدل العالي خسارة إعادة الترميز لكنه لا يعيد التفاصيل غير الموجودة في الفيديو الأصلي. لذلك يوضح toTube معدل الخرج بدون ادعاءات مضللة." }, { title: "ملف MP3 حقيقي", text: "يستخرج FFmpeg الصوت ويرمزه، ثم يتأكد FFprobe من وجود مسار MP3 حقيقي وعدم وجود فيديو في الملف." }], faqs: [{ question: "هل الترميز فعلاً 320 kbps؟", answer: "عند اختياره يتلقى FFmpeg هدف 320 kbps، لكن النتيجة المسموعة تعتمد على المصدر." }, { question: "ما المعدل المناسب للكلام؟", answer: "عادة يكفي 128 أو 192 kbps للمحاضرات والبودكاست والمقابلات." }, { question: "هل يعمل الملف على الهاتف؟", answer: "نعم، تدعم معظم الهواتف والسيارات وأجهزة الكمبيوتر صيغة MP3." }] },
    "youtube-mp4-1080": { home: "الرئيسية", convert: "تحويل إلى MP4", free: "مجاني", verified: "H.264/AAC متحقق", selectable: "360p إلى 1080p", guide: "دليل جودة الفيديو", questions: "الأسئلة الشائعة", related: "صيغ مرتبطة", footer: "تحويل واضح مع فحص الملف النهائي.", title: "YouTube إلى MP4 1080p", accent: "متوافق مع أجهزتك.", description: "نزّل فيديو YouTube عاماً بصيغة MP4 واختر دقة حتى 1080p. يتم فحص كل ملف للتشغيل الموثوق.", sections: [{ title: "اختر الدقة", text: "يقلل 360p حجم الملف، ويناسب 720p معظم شاشات الهاتف، بينما يحافظ 1080p على تفاصيل أكثر عندما يوفرها المصدر فعلاً." }, { title: "لماذا نقول حتى 1080p", text: "لا يصنع toTube دقة غير موجودة. إذا كانت أفضل نسخة عامة 720p فستبقى النتيجة 720p حتى عند اختيار حد 1080p." }, { title: "فحص MP4 H.264 وAAC", text: "بعد التنزيل والدمج يفحص الخادم فيديو H.264 وصوت AAC وyuv420p، ولا يعيد الترميز إلا عند الحاجة للتوافق." }], faqs: [{ question: "هل يمكن الحصول على 1080p حقيقي؟", answer: "نعم عندما يوفر المصدر العام هذه الدقة، وإلا تُستخدم أفضل جودة تحت الحد المختار." }, { question: "لماذا لا تتوفر 4K؟", answer: "يحافظ حد 1080p الحالي على استقرار الخدمة ويمنع وعداً لا يمكن ضمانه لكل مصدر." }, { question: "هل يعمل MP4 على iPhone؟", answer: "تم اختيار H.264/AAC وyuv420p لتوافق واسع مع iPhone وAndroid والتلفاز والكمبيوتر." }] },
  },
  es: {
    "youtube-mp3-320": { home: "Inicio", convert: "Convertir a MP3", free: "Gratis", verified: "Códec verificado", selectable: "128 a 320 kbps", guide: "Guía de calidad de audio", questions: "Preguntas frecuentes", related: "Formatos relacionados", footer: "Conversión transparente con verificación final.", title: "YouTube a MP3 320 kbps", accent: "con codificación de audio real.", description: "Convierte un vídeo público de YouTube a MP3 y elige 128, 192, 256 o 320 kbps. Verificamos el archivo antes de descargarlo.", sections: [{ title: "Elige el bitrate", text: "128 kbps sirve para voz, 192 o 256 equilibran tamaño y sonido, y 320 prioriza la música cuando la fuente lo permite." }, { title: "320 kbps no repara una mala fuente", text: "Un bitrate alto reduce pérdidas adicionales, pero no recupera detalles ausentes. toTube indica el objetivo sin prometer mejorar el original." }, { title: "Un MP3 real", text: "FFmpeg codifica el audio y FFprobe confirma un flujo MP3 verdadero sin pista de vídeo." }], faqs: [{ question: "¿Es realmente 320 kbps?", answer: "Al seleccionarlo, FFmpeg recibe ese objetivo. El resultado depende del audio original." }, { question: "¿Qué bitrate uso para voz?", answer: "128 o 192 kbps suele bastar para clases, podcasts y entrevistas." }, { question: "¿Funciona en el móvil?", answer: "Sí. MP3 es compatible con casi todos los teléfonos y reproductores." }] },
    "youtube-mp4-1080": { home: "Inicio", convert: "Convertir a MP4", free: "Gratis", verified: "H.264/AAC verificado", selectable: "360p a 1080p", guide: "Guía de calidad de vídeo", questions: "Preguntas frecuentes", related: "Formatos relacionados", footer: "Conversión transparente con verificación final.", title: "YouTube a MP4 1080p", accent: "compatible con tus dispositivos.", description: "Descarga un vídeo público de YouTube como MP4 y elige hasta 1080p. Verificamos cada salida para una reproducción fiable.", sections: [{ title: "Elige la resolución", text: "360p reduce el tamaño, 720p sirve para la mayoría de móviles y 1080p conserva más detalle cuando existe en la fuente." }, { title: "Por qué decimos hasta 1080p", text: "toTube no inventa píxeles. Si la mejor versión pública es 720p, el resultado seguirá siendo 720p." }, { title: "MP4 H.264 y AAC verificado", text: "El servidor comprueba vídeo H.264, audio AAC y píxeles yuv420p, y recodifica solo si hace falta." }], faqs: [{ question: "¿Puedo obtener 1080p real?", answer: "Sí, cuando la fuente pública lo ofrece; en caso contrario se usa la mejor calidad inferior." }, { question: "¿Por qué no hay 4K?", answer: "El límite de 1080p mantiene la estabilidad y evita promesas que no pueden garantizarse siempre." }, { question: "¿Funciona con QuickTime?", answer: "H.264/AAC y yuv420p ofrecen amplia compatibilidad con QuickTime, iPhone, Android y TV." }] },
  },
  pt: {
    "youtube-mp3-320": { home: "Início", convert: "Converter para MP3", free: "Grátis", verified: "Codec verificado", selectable: "128 a 320 kbps", guide: "Guia de qualidade de áudio", questions: "Perguntas frequentes", related: "Formatos relacionados", footer: "Conversão transparente com verificação final.", title: "YouTube para MP3 320 kbps", accent: "com codificação de áudio real.", description: "Converta um vídeo público do YouTube para MP3 e escolha 128, 192, 256 ou 320 kbps. O arquivo é verificado antes do download.", sections: [{ title: "Escolha o bitrate", text: "128 kbps serve para voz, 192 ou 256 equilibram tamanho e som, e 320 prioriza música quando a fonte permite." }, { title: "320 kbps não recupera uma fonte ruim", text: "Um bitrate alto reduz perdas adicionais, mas não recria detalhes ausentes. O toTube informa o alvo sem prometer melhorar o original." }, { title: "Um MP3 real", text: "O FFmpeg codifica o áudio e o FFprobe confirma um fluxo MP3 verdadeiro sem vídeo." }], faqs: [{ question: "É realmente 320 kbps?", answer: "Ao selecionar, o FFmpeg recebe esse alvo. O resultado depende do áudio original." }, { question: "Qual bitrate usar para voz?", answer: "128 ou 192 kbps costuma bastar para aulas, podcasts e entrevistas." }, { question: "Funciona no celular?", answer: "Sim. MP3 funciona em quase todos os celulares e players." }] },
    "youtube-mp4-1080": { home: "Início", convert: "Converter para MP4", free: "Grátis", verified: "H.264/AAC verificado", selectable: "360p a 1080p", guide: "Guia de qualidade de vídeo", questions: "Perguntas frequentes", related: "Formatos relacionados", footer: "Conversão transparente com verificação final.", title: "YouTube para MP4 1080p", accent: "compatível com seus aparelhos.", description: "Baixe um vídeo público do YouTube em MP4 e escolha até 1080p. Cada arquivo é verificado para reprodução confiável.", sections: [{ title: "Escolha a resolução", text: "360p reduz o tamanho, 720p serve para a maioria dos celulares e 1080p preserva mais detalhes quando a fonte oferece." }, { title: "Por que dizemos até 1080p", text: "O toTube não inventa pixels. Se a melhor versão pública for 720p, o resultado continuará em 720p." }, { title: "MP4 H.264 e AAC verificado", text: "O servidor verifica vídeo H.264, áudio AAC e yuv420p, recodificando apenas quando necessário." }], faqs: [{ question: "Posso obter 1080p real?", answer: "Sim, quando a fonte pública oferece; caso contrário usamos a melhor qualidade inferior." }, { question: "Por que não há 4K?", answer: "O limite de 1080p mantém a estabilidade e evita promessas que não podem ser garantidas." }, { question: "Funciona no QuickTime?", answer: "H.264/AAC e yuv420p oferecem ampla compatibilidade com QuickTime, iPhone, Android e TV." }] },
  },
  de: {
    "youtube-mp3-320": { home: "Startseite", convert: "In MP3 konvertieren", free: "Kostenlos", verified: "Codec geprüft", selectable: "128 bis 320 kbps", guide: "Audioqualitäts-Leitfaden", questions: "Häufige Fragen", related: "Ähnliche Formate", footer: "Transparente Konvertierung mit abschließender Dateiprüfung.", title: "YouTube zu MP3 320 kbps", accent: "mit echter Audiocodierung.", description: "Konvertiere ein öffentliches YouTube-Video in MP3 und wähle 128, 192, 256 oder 320 kbps. Die Datei wird vor dem Download geprüft.", sections: [{ title: "Bitrate auswählen", text: "128 kbps eignet sich für Sprache, 192 oder 256 gleichen Größe und Klang aus, und 320 bevorzugt Musikqualität, wenn die Quelle sie hergibt." }, { title: "320 kbps repariert keine schlechte Quelle", text: "Eine hohe Bitrate verringert zusätzliche Verluste, stellt aber fehlende Details nicht wieder her. toTube nennt das Ziel ohne falsche Verbesserungsaussagen." }, { title: "Eine echte MP3-Datei", text: "FFmpeg codiert das Audio und FFprobe bestätigt einen echten MP3-Stream ohne Videospur." }], faqs: [{ question: "Ist die MP3 wirklich 320 kbps?", answer: "Bei Auswahl erhält FFmpeg dieses Ziel. Das hörbare Ergebnis hängt von der Quelle ab." }, { question: "Welche Bitrate für Sprache?", answer: "128 oder 192 kbps reicht meist für Vorträge, Podcasts und Interviews." }, { question: "Läuft die Datei auf dem Handy?", answer: "Ja. MP3 wird von fast allen Handys und Playern unterstützt." }] },
    "youtube-mp4-1080": { home: "Startseite", convert: "In MP4 konvertieren", free: "Kostenlos", verified: "H.264/AAC geprüft", selectable: "360p bis 1080p", guide: "Videoqualitäts-Leitfaden", questions: "Häufige Fragen", related: "Ähnliche Formate", footer: "Transparente Konvertierung mit abschließender Dateiprüfung.", title: "YouTube zu MP4 1080p", accent: "für kompatible Wiedergabe.", description: "Lade ein öffentliches YouTube-Video als MP4 und wähle bis zu 1080p. Jede Ausgabe wird für zuverlässige Wiedergabe geprüft.", sections: [{ title: "Auflösung auswählen", text: "360p spart Speicher, 720p passt für die meisten Handys und 1080p bewahrt mehr Details, wenn die Quelle sie anbietet." }, { title: "Warum wir bis zu 1080p sagen", text: "toTube erfindet keine Pixel. Ist die beste öffentliche Version 720p, bleibt das Ergebnis 720p." }, { title: "Geprüftes H.264/AAC-MP4", text: "Der Server prüft H.264-Video, AAC-Audio und yuv420p und codiert nur bei Bedarf neu." }], faqs: [{ question: "Bekomme ich echtes 1080p?", answer: "Ja, wenn die öffentliche Quelle es anbietet; sonst nutzen wir die beste niedrigere Qualität." }, { question: "Warum kein 4K?", answer: "Die 1080p-Grenze hält den Dienst stabil und vermeidet nicht garantierbare Versprechen." }, { question: "Funktioniert es mit QuickTime?", answer: "H.264/AAC und yuv420p bieten breite Kompatibilität mit QuickTime, iPhone, Android und TV." }] },
  },
};

const qualitySupplements: Record<Locale, Record<"audio" | "video", { title: string; text: string }[]>> = {
  fr: {
    audio: [
      { title: "Quel débit pour la musique, la voix ou la voiture ?", text: "Pour une conférence ou un podcast, 128 à 192 kbps offre généralement une écoute claire avec un fichier compact. La musique bénéficie davantage de 256 ou 320 kbps lorsque la source est de bonne qualité. Dans une voiture, sur une clé USB ou un ancien lecteur, MP3 reste le choix le plus sûr. Comparez surtout le résultat sur votre appareil : un débit élevé consomme plus d’espace sans garantir une différence audible dans tous les environnements." },
      { title: "Taille du fichier et durée", text: "À durée égale, un MP3 320 kbps est environ deux fois et demie plus volumineux qu’un fichier 128 kbps. Une heure d’audio représente approximativement 58 Mo à 128 kbps, 86 Mo à 192 kbps et 144 Mo à 320 kbps, hors métadonnées. Ces valeurs sont des estimations utiles pour choisir avant un long enregistrement; la taille exacte dépend de l’encodage et du média source." },
      { title: "Que faire si le MP3 ne se lit pas ?", text: "Téléchargez le fichier jusqu’au bout et vérifiez que son extension est bien .mp3. Essayez ensuite un lecteur récent ou le navigateur avant de relancer la conversion. Un fichier de zéro octet, une durée incohérente ou une page HTML enregistrée à la place du média indique un téléchargement interrompu, pas un problème de débit. toTube contrôle le flux audio final, mais le transfert local peut encore être bloqué par le navigateur ou l’espace disponible." },
    ],
    video: [
      { title: "Quelle résolution pour un téléphone, un ordinateur ou une TV ?", text: "360p économise les données sur une petite connexion, 480p reste lisible sur un téléphone, 720p équilibre netteté et taille, et 1080p convient mieux aux écrans plus grands. La distance de visionnage et la qualité de la source comptent autant que le nombre de pixels. Pour une courte vidéo mobile, 720p est souvent suffisant; pour du texte fin ou une démonstration sur ordinateur, 1080p peut préserver davantage de détails." },
      { title: "Pourquoi le son et l’image sont parfois séparés", text: "Les plateformes diffusent souvent les meilleures qualités vidéo et audio dans des flux distincts. Le serveur doit les télécharger, les synchroniser puis les réunir dans un seul MP4. Une fusion correcte conserve la qualité sans réencoder inutilement. Si les codecs ne sont pas compatibles avec les appareils courants, toTube prépare une sortie H.264/AAC afin d’éviter une vidéo muette, un écran noir ou un fichier refusé par QuickTime." },
      { title: "Diagnostiquer un MP4 flou ou impossible à lire", text: "Vérifiez d’abord la résolution réellement proposée sur la page source. Un choix 1080p agit comme une limite maximale, pas comme une promesse d’agrandissement. Si le fichier ne se lit pas, attendez la fin du téléchargement, contrôlez sa taille et essayez un lecteur récent. Une connexion interrompue peut produire un fichier partiel, tandis qu’une source verticale ou très compressée peut sembler floue même avec une hauteur annoncée élevée." },
    ],
  },
  en: {
    audio: [
      { title: "Which bitrate works for music, speech or a car stereo?", text: "For lectures and podcasts, 128 to 192 kbps normally gives clear speech in a compact file. Music benefits more from 256 or 320 kbps when the source is good enough. MP3 remains the safest option for car stereos, USB drives and older players. Compare the result on the device you actually use: a higher bitrate takes more space and is not automatically audible in every listening environment." },
      { title: "Estimate file size from duration", text: "For the same duration, a 320 kbps MP3 is roughly two and a half times the size of a 128 kbps file. One hour of audio is approximately 58 MB at 128 kbps, 86 MB at 192 kbps and 144 MB at 320 kbps, excluding metadata. These are planning estimates rather than guarantees because exact size depends on the encoder and source." },
      { title: "What if the MP3 does not play?", text: "Let the download finish and confirm that the file ends in .mp3. Try a current media player or the browser before converting again. A zero-byte file, implausible duration or saved HTML page points to an interrupted transfer rather than a bitrate problem. toTube checks the final audio stream, but the local transfer can still be stopped by browser settings or insufficient device storage." },
    ],
    video: [
      { title: "Which resolution fits a phone, computer or TV?", text: "360p saves data on slow connections, 480p remains usable on a phone, 720p balances sharpness and size, and 1080p is better for larger screens. Viewing distance and source quality matter as much as pixel count. A short mobile clip is often fine at 720p, while small text and desktop demonstrations can benefit from genuine 1080p detail." },
      { title: "Why video and audio may arrive as separate streams", text: "Platforms often deliver their best picture and sound in separate streams. The server downloads them, keeps them synchronized and merges them into one MP4. A clean merge preserves quality without unnecessary re-encoding. When the supplied codecs are not broadly compatible, toTube prepares H.264/AAC output to prevent silent video, a black screen or a file rejected by QuickTime." },
      { title: "Troubleshoot a blurry or unplayable MP4", text: "Check the resolution genuinely offered by the source page first. Selecting 1080p sets a maximum, not a promise to upscale. If playback fails, wait for the full download, check the file size and try a current player. An interrupted connection can leave a partial file, while a vertical or heavily compressed source may still look soft even when its reported height is high." },
    ],
  },
  ar: {
    audio: [
      { title: "أي معدل يناسب الموسيقى أو الكلام أو السيارة؟", text: "يكفي 128 إلى 192 kbps عادة للمحاضرات والبودكاست مع حجم صغير. تستفيد الموسيقى أكثر من 256 أو 320 kbps عندما تكون جودة المصدر جيدة. تبقى MP3 الخيار الأكثر توافقاً للسيارة وذاكرة USB والأجهزة القديمة. اختبر الملف على جهازك الفعلي، فالمعدل الأعلى يحتاج مساحة أكبر ولا يعني دائماً فرقاً مسموعاً." },
      { title: "تقدير حجم الملف من المدة", text: "يكون ملف 320 kbps للمدة نفسها أكبر بنحو مرتين ونصف من 128 kbps. تمثل ساعة صوت تقريباً 58 ميغابايت عند 128 و86 ميغابايت عند 192 و144 ميغابايت عند 320، من دون البيانات الوصفية. هذه أرقام تقريبية للتخطيط لأن الحجم الدقيق يعتمد على الترميز والمصدر." },
      { title: "ماذا تفعل إذا لم يعمل MP3؟", text: "انتظر اكتمال التنزيل وتأكد من امتداد .mp3، ثم جرب مشغلاً حديثاً أو المتصفح. الملف الفارغ أو المدة غير المنطقية أو حفظ صفحة HTML يدل على نقل منقطع وليس مشكلة في معدل الصوت. يفحص toTube مسار الصوت النهائي، لكن إعدادات المتصفح أو نقص مساحة الجهاز قد يوقفان التنزيل المحلي." },
    ],
    video: [
      { title: "أي دقة تناسب الهاتف أو الكمبيوتر أو التلفاز؟", text: "توفر 360p البيانات، وتناسب 480p شاشة الهاتف، وتوازن 720p بين الوضوح والحجم، بينما تلائم 1080p الشاشات الأكبر. تؤثر مسافة المشاهدة وجودة المصدر بقدر عدد البكسلات. غالباً تكفي 720p لمقطع هاتف قصير، أما النص الصغير وشرح سطح المكتب فيستفيدان من 1080p حقيقية." },
      { title: "لماذا يصل الصوت والفيديو في مسارين؟", text: "ترسل المنصات أفضل صورة وصوت في مسارين منفصلين غالباً. ينزلهما الخادم ويحافظ على تزامنهما ثم يدمجهما في MP4 واحد. يحافظ الدمج على الجودة من دون إعادة ترميز غير ضرورية. وعندما لا تكون الترميزات متوافقة على نطاق واسع، يجهز toTube ملف H.264/AAC لتجنب شاشة سوداء أو فيديو بلا صوت." },
      { title: "حل مشكلة MP4 الضبابي أو غير القابل للتشغيل", text: "تحقق أولاً من الدقة الحقيقية في صفحة المصدر. اختيار 1080p يحدد سقفاً ولا يعني تكبير الفيديو. عند فشل التشغيل انتظر اكتمال التنزيل وافحص حجم الملف وجرب مشغلاً حديثاً. قد يترك انقطاع الاتصال ملفاً ناقصاً، كما قد يبدو المصدر العمودي أو المضغوط ضبابياً رغم ارتفاع عدد البكسلات المعلن." },
    ],
  },
  es: {
    audio: [
      { title: "¿Qué bitrate usar para música, voz o el coche?", text: "Para clases y podcasts, 128 a 192 kbps suele ofrecer voz clara en un archivo compacto. La música aprovecha mejor 256 o 320 kbps cuando la fuente es buena. MP3 sigue siendo la opción más compatible para coches, memorias USB y reproductores antiguos. Compara el resultado en tu dispositivo: un bitrate mayor ocupa más y no siempre produce una diferencia audible." },
      { title: "Calcula el tamaño según la duración", text: "Con la misma duración, un MP3 de 320 kbps ocupa unas dos veces y media más que uno de 128 kbps. Una hora equivale aproximadamente a 58 MB en 128, 86 MB en 192 y 144 MB en 320, sin contar metadatos. Son estimaciones para planificar; el tamaño exacto depende del codificador y la fuente." },
      { title: "¿Qué hacer si el MP3 no se reproduce?", text: "Espera a que termine la descarga y confirma la extensión .mp3. Prueba un reproductor reciente o el navegador antes de convertir otra vez. Un archivo vacío, una duración incoherente o una página HTML guardada indican una transferencia interrumpida. toTube comprueba el flujo de audio, pero el navegador o la falta de espacio todavía pueden detener la descarga local." },
    ],
    video: [
      { title: "¿Qué resolución sirve para móvil, ordenador o TV?", text: "360p ahorra datos, 480p funciona en un móvil, 720p equilibra nitidez y tamaño y 1080p se adapta mejor a pantallas grandes. La distancia y la fuente importan tanto como los píxeles. Un clip móvil suele verse bien en 720p; el texto pequeño o una demostración de escritorio pueden beneficiarse de 1080p real." },
      { title: "Por qué el audio y el vídeo pueden llegar separados", text: "Las plataformas suelen entregar la mejor imagen y el mejor sonido en flujos distintos. El servidor los descarga, sincroniza y combina en un solo MP4. Una unión correcta conserva calidad sin recodificar de forma innecesaria. Si los códecs no son compatibles, toTube prepara H.264/AAC para evitar vídeo sin sonido, pantalla negra o rechazo de QuickTime." },
      { title: "Soluciona un MP4 borroso o incompatible", text: "Comprueba primero la resolución ofrecida por la fuente. Seleccionar 1080p fija un máximo, no promete ampliar. Si no se reproduce, espera la descarga completa, revisa el tamaño y prueba un reproductor actual. Una conexión interrumpida deja archivos parciales y una fuente vertical o muy comprimida puede verse suave aunque declare muchos píxeles." },
    ],
  },
  pt: {
    audio: [
      { title: "Qual bitrate usar para música, voz ou som do carro?", text: "Para aulas e podcasts, 128 a 192 kbps normalmente oferece voz clara com arquivo compacto. Música aproveita melhor 256 ou 320 kbps quando a fonte é boa. MP3 continua a opção mais compatível para carros, USB e players antigos. Compare no aparelho real: bitrate maior ocupa mais espaço e nem sempre gera diferença audível." },
      { title: "Estime o tamanho pela duração", text: "Na mesma duração, um MP3 de 320 kbps ocupa cerca de duas vezes e meia o tamanho de 128 kbps. Uma hora representa aproximadamente 58 MB em 128, 86 MB em 192 e 144 MB em 320, sem metadados. São estimativas para planejamento; o tamanho exato depende do codificador e da fonte." },
      { title: "O que fazer se o MP3 não tocar?", text: "Espere o download terminar e confirme a extensão .mp3. Teste um player atual ou o navegador antes de converter novamente. Arquivo vazio, duração incoerente ou página HTML salva indicam transferência interrompida. O toTube verifica o fluxo de áudio, mas o navegador ou a falta de espaço ainda podem interromper o download local." },
    ],
    video: [
      { title: "Qual resolução usar no celular, computador ou TV?", text: "360p economiza dados, 480p funciona no celular, 720p equilibra nitidez e tamanho e 1080p atende melhor a telas grandes. Distância e qualidade da fonte importam tanto quanto pixels. Um clipe móvel costuma ficar bom em 720p; texto pequeno e demonstrações de desktop podem aproveitar 1080p verdadeiro." },
      { title: "Por que áudio e vídeo podem vir separados", text: "As plataformas frequentemente entregam a melhor imagem e o melhor som em fluxos distintos. O servidor baixa, sincroniza e une ambos em um MP4. A união correta preserva qualidade sem recodificar sem necessidade. Quando os codecs não são amplamente compatíveis, o toTube prepara H.264/AAC para evitar vídeo mudo, tela preta ou rejeição pelo QuickTime." },
      { title: "Resolva um MP4 borrado ou incompatível", text: "Confira primeiro a resolução realmente oferecida pela fonte. Selecionar 1080p define um máximo, não promete ampliar. Se não tocar, espere o download completo, verifique o tamanho e teste um player recente. Uma conexão interrompida deixa arquivo parcial, e uma fonte vertical ou muito comprimida pode continuar suave mesmo com altura elevada." },
    ],
  },
  de: {
    audio: [
      { title: "Welche Bitrate für Musik, Sprache oder Autoradio?", text: "Für Vorträge und Podcasts liefern 128 bis 192 kbps meist klare Sprache bei kompakter Größe. Musik profitiert bei guter Quelle eher von 256 oder 320 kbps. MP3 bleibt für Autoradios, USB-Sticks und ältere Player am kompatibelsten. Vergleiche auf dem echten Zielgerät: Eine höhere Bitrate braucht mehr Platz und ist nicht in jeder Umgebung hörbar besser." },
      { title: "Dateigröße aus der Dauer abschätzen", text: "Bei gleicher Dauer ist eine 320-kbps-MP3 ungefähr zweieinhalbmal so groß wie eine Datei mit 128 kbps. Eine Stunde entspricht grob 58 MB bei 128, 86 MB bei 192 und 144 MB bei 320 kbps, ohne Metadaten. Das sind Planungswerte; die genaue Größe hängt von Encoder und Quelle ab." },
      { title: "Was tun, wenn die MP3 nicht läuft?", text: "Warte den vollständigen Download ab und prüfe die Endung .mp3. Teste einen aktuellen Player oder Browser, bevor du erneut konvertierst. Eine leere Datei, unplausible Dauer oder gespeicherte HTML-Seite deutet auf eine unterbrochene Übertragung. toTube prüft den Audiostream, doch Browser-Einstellungen oder fehlender Speicher können den lokalen Transfer stoppen." },
    ],
    video: [
      { title: "Welche Auflösung für Handy, Computer oder TV?", text: "360p spart Daten, 480p reicht auf dem Handy, 720p balanciert Schärfe und Größe und 1080p passt besser zu großen Bildschirmen. Abstand und Quellqualität zählen ebenso wie Pixel. Für kurze mobile Clips genügt oft 720p; kleine Schrift und Desktop-Demos profitieren von echten 1080p-Details." },
      { title: "Warum Bild und Ton getrennt geliefert werden", text: "Plattformen liefern bestes Bild und besten Ton oft als getrennte Streams. Der Server lädt beide, hält sie synchron und führt sie zu einem MP4 zusammen. Sauberes Zusammenführen bewahrt Qualität ohne unnötige Neucodierung. Sind die Codecs nicht breit kompatibel, bereitet toTube H.264/AAC vor, um stummes Video, schwarzen Bildschirm oder QuickTime-Ablehnung zu vermeiden." },
      { title: "Unscharfes oder unspielbares MP4 prüfen", text: "Prüfe zuerst die tatsächlich angebotene Quellauflösung. 1080p setzt eine Obergrenze und verspricht kein Hochskalieren. Warte bei Wiedergabeproblemen den vollständigen Download ab, kontrolliere die Größe und teste einen aktuellen Player. Eine unterbrochene Verbindung hinterlässt Teildateien; stark komprimierte oder vertikale Quellen können trotz hoher gemeldeter Pixelzahl weich wirken." },
    ],
  },
};

export function localizedQualityMetadata(locale: Locale, page: QualityPageId) {
  const content = qualityContent[locale][page];
  return { title: `${content.title} — ${content.accent.replace(/\.$/, "")} | toTube`, description: content.description };
}

export function LocalizedQualityPage({ locale, page }: { locale: Locale; page: QualityPageId }) {
  const content = qualityContent[locale][page];
  const sections = [...content.sections, ...qualitySupplements[locale][page === "youtube-mp3-320" ? "audio" : "video"]];
  const copy = homeCopy[locale];
  const canonical = `https://totube.online${qualityPagePath(locale, page)}`;
  const otherPage: QualityPageId = page === "youtube-mp3-320" ? "youtube-mp4-1080" : "youtube-mp3-320";
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: content.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: content.home, item: `https://totube.online/${locale}` }, { "@type": "ListItem", position: 2, name: content.title, item: canonical }] };
  const applicationSchema = { "@context": "https://schema.org", "@type": "WebApplication", name: `${content.title} by toTube`, url: canonical, description: content.description, applicationCategory: "MultimediaApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "EUR" }, featureList: [content.selectable, content.verified, "Temporary private download link"] };
  const MainIcon = page === "youtube-mp3-320" ? FileAudio : FileVideo;

  return <main className="seo-page" dir={copy.dir}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(applicationSchema) }} />
    <header className="site-header seo-header"><Link href={`/${locale}`} className="brand"><span className="brand-mark"><Play size={15} fill="currentColor" /></span><span>totube</span></Link><ToolNavigation locale={locale} currentQuality={page} /><Link className="nav-cta" href={`/${locale}#converter`}>{content.convert} <ArrowRight size={15} /></Link></header>
    <section className="seo-hero"><nav className="breadcrumbs"><Link href={`/${locale}`}>{content.home}</Link><span>/</span><span>{content.title}</span></nav><span className="section-kicker">{content.guide}</span><h1>{content.title}<br /><em>{content.accent}</em></h1><p>{content.description}</p><Link href={`/${locale}#converter`} className="seo-primary-cta">{content.convert} <ArrowRight size={18} /></Link><div className="seo-trust"><span><Check size={15} /> {content.free}</span><span><Check size={15} /> {content.verified}</span><span><Check size={15} /> {content.selectable}</span></div></section>
    <div className="seo-ad-band"><AdBanner adKey={AD_KEYS.leaderboard} width={728} height={90} label={copy.ad} /></div>
    <section className="seo-benefits"><article><span><MainIcon /></span><h2>{content.title}</h2><p>{content.description}</p></article><article><span><Gauge /></span><h2>{content.selectable}</h2><p>{content.sections[0].text}</p></article><article><span><ShieldCheck /></span><h2>{content.verified}</h2><p>{content.sections[2].text}</p></article></section>
    <article className="seo-article"><div className="seo-article-intro"><span className="section-kicker">{content.guide}</span><p>{content.description}</p></div><div className="seo-copy">{sections.map((section) => <section key={section.title}><h2>{section.title}</h2><p>{section.text}</p></section>)}<aside className="seo-callout"><span><MainIcon /></span><div><strong>{content.selectable}</strong><p>{content.verified}</p></div><Link href={`/${locale}#converter`}>{content.convert} <ArrowRight size={15} /></Link></aside></div></article>
    <div className="seo-ad-band compact"><AdBanner adKey={AD_KEYS.compact} width={468} height={60} label={copy.ad} /></div>
    <section className="seo-faq"><div><span className="section-kicker">{content.questions}</span><h2>{content.questions}</h2></div><div className="seo-faq-list">{content.faqs.map((faq, index) => <details key={faq.question} open={index === 0}><summary><span>{String(index + 1).padStart(2, "0")}</span>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></section>
    <section className="related-section"><span className="section-kicker">{content.related}</span><h2>{content.related}</h2><div><Link href={qualityPagePath(locale, otherPage)}><strong>{qualityContent[locale][otherPage].title}</strong><p>{qualityContent[locale][otherPage].description}</p><ArrowRight size={17} /></Link><Link href={platformPath(locale, "youtube")}><strong>YouTube Downloader</strong><p>{copy.metaDescription}</p><ArrowRight size={17} /></Link><Link href={`/${locale}#converter`}><strong>{content.convert}</strong><p>{content.selectable} · {content.verified}</p><ArrowRight size={17} /></Link></div></section>
    <ToolFooter locale={locale} text={content.footer} />
  </main>;
}
